export const SECURITY_CONSTANTS = {
  TOKEN_REFRESH_BUFFER_MS: 5 * 60 * 1000,
  SESSION_TIMEOUT_MS: 30 * 60 * 1000,
  INACTIVITY_TIMEOUT_MS: 15 * 60 * 1000,
  BIOMETRIC_TIMEOUT_MS: 5 * 60 * 1000,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MS: 15 * 60 * 1000,
  OTP_LENGTH: 6,
  OTP_EXPIRY_SECONDS: 300,
  PASSWORD_MIN_LENGTH: 8,
  ACCESS_TOKEN_LIFETIME_MS: 5 * 60 * 1000,
  REFRESH_TOKEN_LIFETIME_MS: 35 * 24 * 60 * 60 * 1000,
  MAX_CONCURRENT_REFRESH: 1,
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
  ALLOWED_DOCUMENT_TYPES: ['application/pdf', 'image/jpeg', 'image/png'],
  ALLOWED_SCHEMES: ['https', 'rentsecure'],
  DEEP_LINK_HOSTS: ['app.rentsecureapp.com', 'app.rentsecure.com'],
  SENSITIVE_FIELDS: [
    'password',
    'token',
    'secret',
    'access',
    'refresh',
    'authorization',
    'cookie',
    'otp',
    'cvv',
    'upi',
    'bank_account',
    'ifsc',
    'razorpay_secret',
    'cashfree_secret',
  ],
  SENSITIVE_HEADERS: [
    'authorization',
    'cookie',
    'x-csrf-token',
    'x-api-key',
    'x-razorpay-signature',
    'x-cashfree-signature',
  ],
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MAX_REQUEST_BODY_BYTES: 5 * 1024 * 1024,
} as const;

export type SecurityConstants = typeof SECURITY_CONSTANTS;
