export const SENTRY_ENABLED_KEY = 'EXPO_PUBLIC_ENABLE_CRASH_REPORTING';
export const SENTRY_DSN_KEY = 'EXPO_PUBLIC_SENTRY_DSN';
export const SENTRY_ENVIRONMENT_KEY = 'EXPO_PUBLIC_APP_ENV';
export const SENTRY_TRACES_SAMPLE_RATE_DEVELOPMENT = 1.0;
export const SENTRY_TRACES_SAMPLE_RATE_STAGING = 0.2;
export const SENTRY_TRACES_SAMPLE_RATE_PRODUCTION = 0.1;
export const SENTRY_REPLAY_SESSION_SAMPLE_RATE_DEVELOPMENT = 0.0;
export const SENTRY_REPLAY_SESSION_SAMPLE_RATE_STAGING = 0.0;
export const SENTRY_REPLAY_SESSION_SAMPLE_RATE_PRODUCTION = 0.0;
export const SENTRY_REPLAY_ERROR_SAMPLE_RATE = 1.0;
export const SENTRY_ATTACH_STACKTRACE = true;
export const SENTRY_ENABLE_AUTO_SESSION_TRACKING = true;
export const SENTRY_SESSION_TRACKING_INTERVAL_MS = 30000;

export const SENTRY_IGNORED_ERROR_MESSAGES = [
  'Network request failed',
  'No internet connection',
  'Request cancelled',
  'Request queued - offline',
];

export const SENTRY_IGNORED_ERROR_CODES = [
  'ECONNABORTED',
  'ETIMEDOUT',
  'ENOTFOUND',
  'ECONNREFUSED',
  'ECONNRESET',
];
