export const NOTIFICATION_CATEGORIES = {
  RENT_DUE: 'rent_due',
  RENT_PAID: 'rent_paid',
  RENT_OVERDUE: 'rent_overdue',
  MAINTENANCE_ASSIGNED: 'maintenance_assigned',
  MAINTENANCE_UPDATED: 'maintenance_updated',
  MAINTENANCE_COMPLETED: 'maintenance_completed',
  VISITOR_REQUEST: 'visitor_request',
  VISITOR_APPROVED: 'visitor_approved',
  VISITOR_CHECKED_IN: 'visitor_checked_in',
  VISITOR_CHECKED_OUT: 'visitor_checked_out',
  AGREEMENT_EXPIRING: 'agreement_expiring',
  AGREEMENT_SIGNED: 'agreement_signed',
  AGREEMENT_CREATED: 'agreement_created',
  SUBSCRIPTION_EXPIRING: 'subscription_expiring',
  SUBSCRIPTION_RENEWED: 'subscription_renewed',
  SUBSCRIPTION_CANCELLED: 'subscription_cancelled',
  PAYMENT_SUCCESS: 'payment_success',
  PAYMENT_FAILED: 'payment_failed',
  PAYOUT_SUCCESS: 'payout_success',
  PAYOUT_FAILED: 'payout_failed',
  DOCUMENT_UPLOADED: 'document_uploaded',
  KYC_COMPLETED: 'kyc_completed',
  ONBOARDING_INVITE: 'onboarding_invite',
  SYSTEM: 'system',
  GENERAL: 'general',
} as const;

export const NOTIFICATION_TITLE_PATTERNS: Record<string, RegExp[]> = {
  [NOTIFICATION_CATEGORIES.RENT_DUE]: [/rent.*due/i, /due.*rent/i, /new rent due/i],
  [NOTIFICATION_CATEGORIES.RENT_PAID]: [/rent.*paid/i, /paid.*rent/i, /rent payment.*success/i],
  [NOTIFICATION_CATEGORIES.RENT_OVERDUE]: [/rent.*overdue/i, /overdue.*rent/i, /late rent/i],
  [NOTIFICATION_CATEGORIES.MAINTENANCE_ASSIGNED]: [/maintenance.*assigned/i, /assigned.*maintenance/i],
  [NOTIFICATION_CATEGORIES.MAINTENANCE_UPDATED]: [/maintenance.*updated/i, /updated.*maintenance/i],
  [NOTIFICATION_CATEGORIES.MAINTENANCE_COMPLETED]: [/maintenance.*completed/i, /completed.*maintenance/i],
  [NOTIFICATION_CATEGORIES.VISITOR_REQUEST]: [/visitor.*request/i, /new visitor/i, /visitor.*pending/i],
  [NOTIFICATION_CATEGORIES.VISITOR_APPROVED]: [/visitor.*approved/i, /approved.*visitor/i],
  [NOTIFICATION_CATEGORIES.VISITOR_CHECKED_IN]: [/visitor.*checked.?in/i, /visitor.*arrived/i],
  [NOTIFICATION_CATEGORIES.VISITOR_CHECKED_OUT]: [/visitor.*checked.?out/i, /visitor.*departed/i],
  [NOTIFICATION_CATEGORIES.AGREEMENT_EXPIRING]: [/agreement.*expir/i, /expir.*agreement/i],
  [NOTIFICATION_CATEGORIES.AGREEMENT_SIGNED]: [/agreement.*signed/i, /signed.*agreement/i],
  [NOTIFICATION_CATEGORIES.AGREEMENT_CREATED]: [/agreement.*created/i, /new agreement/i],
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_EXPIRING]: [/subscription.*expir/i, /plan.*expir/i],
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_RENEWED]: [/subscription.*renew/i, /plan.*renew/i],
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_CANCELLED]: [/subscription.*cancel/i, /plan.*cancel/i],
  [NOTIFICATION_CATEGORIES.PAYMENT_SUCCESS]: [/payment.*success/i, /payment.*completed/i, /paid.*success/i],
  [NOTIFICATION_CATEGORIES.PAYMENT_FAILED]: [/payment.*fail/i, /payment.*error/i],
  [NOTIFICATION_CATEGORIES.PAYOUT_SUCCESS]: [/payout.*success/i, /payout.*completed/i],
  [NOTIFICATION_CATEGORIES.PAYOUT_FAILED]: [/payout.*fail/i, /payout.*error/i],
  [NOTIFICATION_CATEGORIES.DOCUMENT_UPLOADED]: [/document.*upload/i, /new document/i],
  [NOTIFICATION_CATEGORIES.KYC_COMPLETED]: [/kyc.*completed/i, /kyc.*approved/i, /verification.*completed/i],
  [NOTIFICATION_CATEGORIES.ONBOARDING_INVITE]: [/onboarding/i, /welcome.*rentsecure/i, /invite/i],
};

export const NOTIFICATION_ROUTE_MAP: Record<string, { route: string; resourceType?: string }> = {
  [NOTIFICATION_CATEGORIES.RENT_DUE]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.RENT_PAID]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.RENT_OVERDUE]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.MAINTENANCE_ASSIGNED]: { route: '/(drawer)/(tabs)/maintenance', resourceType: 'maintenance' },
  [NOTIFICATION_CATEGORIES.MAINTENANCE_UPDATED]: { route: '/(drawer)/(tabs)/maintenance', resourceType: 'maintenance' },
  [NOTIFICATION_CATEGORIES.MAINTENANCE_COMPLETED]: { route: '/(drawer)/(tabs)/maintenance', resourceType: 'maintenance' },
  [NOTIFICATION_CATEGORIES.VISITOR_REQUEST]: { route: '/(drawer)/(tabs)/visitors', resourceType: 'visitor' },
  [NOTIFICATION_CATEGORIES.VISITOR_APPROVED]: { route: '/(drawer)/(tabs)/visitors', resourceType: 'visitor' },
  [NOTIFICATION_CATEGORIES.VISITOR_CHECKED_IN]: { route: '/(drawer)/(tabs)/visitors', resourceType: 'visitor' },
  [NOTIFICATION_CATEGORIES.VISITOR_CHECKED_OUT]: { route: '/(drawer)/(tabs)/visitors', resourceType: 'visitor' },
  [NOTIFICATION_CATEGORIES.AGREEMENT_EXPIRING]: { route: '/(drawer)/(tabs)/agreements', resourceType: 'agreement' },
  [NOTIFICATION_CATEGORIES.AGREEMENT_SIGNED]: { route: '/(drawer)/(tabs)/agreements', resourceType: 'agreement' },
  [NOTIFICATION_CATEGORIES.AGREEMENT_CREATED]: { route: '/(drawer)/(tabs)/agreements', resourceType: 'agreement' },
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_EXPIRING]: { route: '/(drawer)/(tabs)/subscription', resourceType: 'subscription' },
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_RENEWED]: { route: '/(drawer)/(tabs)/subscription', resourceType: 'subscription' },
  [NOTIFICATION_CATEGORIES.SUBSCRIPTION_CANCELLED]: { route: '/(drawer)/(tabs)/subscription', resourceType: 'subscription' },
  [NOTIFICATION_CATEGORIES.PAYMENT_SUCCESS]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.PAYMENT_FAILED]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.PAYOUT_SUCCESS]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.PAYOUT_FAILED]: { route: '/(drawer)/(tabs)/payments', resourceType: 'rent_record' },
  [NOTIFICATION_CATEGORIES.DOCUMENT_UPLOADED]: { route: '/(drawer)/(tabs)/buildings', resourceType: 'document' },
  [NOTIFICATION_CATEGORIES.KYC_COMPLETED]: { route: '/(drawer)/(tabs)/renters', resourceType: 'renter' },
  [NOTIFICATION_CATEGORIES.ONBOARDING_INVITE]: { route: '/(auth)/register', resourceType: 'renter' },
  [NOTIFICATION_CATEGORIES.SYSTEM]: { route: '/(drawer)/(tabs)/notifications/list' },
  [NOTIFICATION_CATEGORIES.GENERAL]: { route: '/(drawer)/(tabs)/notifications/list' },
};
