export const ROUTE_GROUPS = {
  AUTH: 'auth',
  DRAWER: 'drawer',
  PUBLIC: 'public',
} as const;

export const AUTH_ROUTES = [
  '/(auth)/welcome',
  '/(auth)/login',
  '/(auth)/register',
  '/(auth)/forgot-password',
  '/(auth)/otp',
  '/(auth)/verify-otp',
  '/(auth)/reset-password',
  '/(auth)/create-password',
  '/(auth)/biometric-setup',
  '/(auth)/session-expired',
  '/(auth)/maintenance',
] as const;

export const PROTECTED_BASE = '/(drawer)';
export const AUTH_BASE = '/(auth)';
export const PUBLIC_ROUTES = ['/splash', '/not-found'] as const;

export const ROUTE_NAMES = {
  SPLASH: 'splash',
  WELCOME: 'welcome',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASSWORD: 'forgot-password',
  OTP: 'otp',
  VERIFY_OTP: 'verify-otp',
  RESET_PASSWORD: 'reset-password',
  CREATE_PASSWORD: 'create-password',
  BIOMETRIC_SETUP: 'biometric-setup',
  SESSION_EXPIRED: 'session-expired',
  MAINTENANCE: 'maintenance',
  DASHBOARD: 'dashboard',
  DASHBOARD_OWNER: 'dashboard-owner',
  DASHBOARD_CARETAKER: 'dashboard-caretaker',
  DASHBOARD_RENTER: 'dashboard-renter',
  PROPERTIES: 'properties',
  PROPERTIES_OWNER: 'properties-owner',
  BUILDINGS: 'buildings',
  BUILDINGS_LIST: 'buildings-list',
  BUILDING_DETAIL: 'building-detail',
  BUILDING_ADD: 'building-add',
  UNITS: 'units',
  UNITS_LIST: 'units-list',
  UNIT_DETAIL: 'unit-detail',
  UNIT_ADD: 'unit-add',
  RENTERS: 'renters',
  RENTERS_LIST: 'renters-list',
  RENTER_DETAIL: 'renter-detail',
  RENTER_ADD: 'renter-add',
  CARETAKERS: 'caretakers',
  CARETAKERS_LIST: 'caretakers-list',
  CARETAKER_DETAIL: 'caretaker-detail',
  CARETAKER_ADD: 'caretaker-add',
  PAYMENTS: 'payments',
  PAYMENTS_OWNER: 'payments-owner',
  PAYMENTS_RENTER: 'payments-renter',
  PAY_RENT: 'pay-rent',
  RENT_RECORD_DETAIL: 'rent-record-detail',
  RENT_DUE: 'rent-due',
  RENT_HISTORY: 'rent-history',
  AGREEMENTS: 'agreements',
  AGREEMENTS_LIST: 'agreements-list',
  AGREEMENT_DETAIL: 'agreement-detail',
  MAINTENANCE_LIST: 'maintenance-list',
  MAINTENANCE_DETAIL: 'maintenance-detail',
  MAINTENANCE_CREATE: 'maintenance-create',
  MAINTENANCE_DASHBOARD: 'maintenance-dashboard',
  VISITORS: 'visitors',
  VISITORS_LIST: 'visitors-list',
  VISITOR_DETAIL: 'visitor-detail',
  VISITOR_CREATE: 'visitor-create',
  VISITOR_ENTRY: 'visitor-entry',
  VISITOR_EXIT: 'visitor-exit',
  VISITOR_QR_DISPLAY: 'visitor-qr-display',
  VISITOR_QR_SCANNER: 'visitor-qr-scanner',
  VISITOR_VERIFY: 'visitor-verify',
  NOTIFICATIONS: 'notifications',
  NOTIFICATIONS_LIST: 'notifications-list',
  REPORTS: 'reports',
  REPORTS_FINANCIAL: 'reports-financial',
  SUBSCRIPTION: 'subscription',
  SUBSCRIPTION_PLANS: 'subscription-plans',
  SUBSCRIPTION_CURRENT: 'subscription-current',
  SUBSCRIPTION_UPGRADE: 'subscription-upgrade',
  SUBSCRIPTION_DOWNGRADE: 'subscription-downgrade',
  SUBSCRIPTION_CANCEL: 'subscription-cancel',
  SUBSCRIPTION_RENEW: 'subscription-renew',
  SUBSCRIPTION_INVOICES: 'subscription-invoices',
  SUBSCRIPTION_ADD_ONS: 'subscription-add-ons',
  SUBSCRIPTION_USAGE: 'subscription-usage',
  SUBSCRIPTION_PAYMENT_HISTORY: 'subscription-payment-history',
  SUBSCRIPTION_PAYMENT_STATUS: 'subscription-payment-status',
  SUBSCRIPTION_EXPIRY: 'subscription-expiry',
  SUBSCRIPTION_COMPARE: 'subscription-compare',
  AI_ASSISTANT: 'ai-assistant',
  AI_ASSISTANT_CHAT: 'ai-assistant-chat',
  SEARCH: 'search',
  SETTINGS: 'settings',
  SETTINGS_INDEX: 'settings-index',
  SETTINGS_PROFILE: 'settings-profile',
  SETTINGS_SECURITY: 'settings-security',
  SETTINGS_NOTIFICATIONS: 'settings-notifications',
  SETTINGS_DEVICES: 'settings-devices',
  SETTINGS_LANGUAGE: 'settings-language',
  SETTINGS_THEME: 'settings-theme',
  SETTINGS_PRIVACY: 'settings-privacy',
  SETTINGS_ABOUT: 'settings-about',
  SETTINGS_HELP: 'settings-help',
  SETTINGS_DELETE_ACCOUNT: 'settings-delete-account',
  SETTINGS_DEACTIVATE_ACCOUNT: 'settings-deactivate-account',
  SETTINGS_LOGIN_SESSIONS: 'settings-login-sessions',
  SETTINGS_EDIT_PROFILE: 'settings-edit-profile',
  PROFILE: 'profile',
  PROFILE_VIEW: 'profile-view',
  SUPPORT: 'support',
  SUPPORT_TICKETS: 'support-tickets',
  NOT_FOUND: 'not-found',
} as const;

export type RouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES];
