export const PAYMENT_CONSTANTS = {
  API: {
    LIST: '/payments/',
    DETAIL: (id: number | string) => `/payments/${id}/`,
    CREATE: '/payments/',
    UPDATE: (id: number | string) => `/payments/${id}/`,
    DELETE: (id: number | string) => `/payments/${id}/`,
    INITIATE: '/payments/initiate/',
    VERIFY: '/payments/verify/',
    REFUND: (id: number | string) => `/payments/${id}/refund/`,
    HISTORY: '/payments/history/',
    OVERDUE: '/payments/overdue/',
    PENDING: '/payments/pending/',
    FAILED: '/payments/failed/',
    ANALYTICS: '/payments/analytics/',
    TIMELINE: (id: number | string) => `/payments/${id}/timeline/`,
    RETRY: (id: number | string) => `/payments/${id}/retry/`,
    CANCEL: (id: number | string) => `/payments/${id}/cancel/`,
    BULK_RETRY: '/payments/bulk-retry/',
    BULK_CANCEL: '/payments/bulk-cancel/',
    PAYMENT_LINK: (id: number | string) => `/payments/${id}/payment-link/`,
    REGENERATE_LINK: (id: number | string) => `/payments/${id}/regenerate-link/`,
    QR_CODE: (id: number | string) => `/payments/${id}/qr-code/`,
    SEND_REMINDER: (id: number | string) => `/payments/${id}/send-reminder/`,
    BULK_REMINDER: '/payments/bulk-remind/',
    REMINDER_HISTORY: (id: number | string) => `/payments/${id}/reminder-history/`,
    COLLECT: '/payments/collect/',
    RECEIPTS: '/payments/receipts/',
    RECEIPT_DETAIL: (id: number | string) => `/payments/${id}/receipt/`,
    EXPORT: '/payments/export/',
  } as const,
  INVOICES: {
    LIST: '/invoices/',
    DETAIL: (id: number | string) => `/invoices/${id}/`,
    CREATE: '/invoices/',
    UPDATE: (id: number | string) => `/invoices/${id}/`,
    DELETE: (id: number | string) => `/invoices/${id}/`,
    DOWNLOAD: (id: number | string) => `/invoices/${id}/download/`,
    SEND: (id: number | string) => `/invoices/${id}/send/`,
    MARK_PAID: (id: number | string) => `/invoices/${id}/mark-paid/`,
    PREVIEW: (id: number | string) => `/invoices/${id}/preview/`,
    SHARE: (id: number | string) => `/invoices/${id}/share/`,
    SEARCH: '/invoices/search/',
    STATS: '/invoices/stats/',
    BULK_GENERATE: '/invoices/bulk-generate/',
  } as const,
  PAYOUTS: {
    LIST: '/payouts/',
    DETAIL: (id: number | string) => `/payouts/${id}/`,
    SUMMARY: '/payouts/summary/',
    RETRY: (id: number | string) => `/payouts/${id}/retry/`,
    BULK_RETRY: '/payouts/bulk-retry/',
  } as const,
  REPORTS: {
    PAYMENT: '/reports/payment/',
    FINANCIAL: '/reports/financial/',
    EXPORT: '/reports/export/',
  } as const,
  REFUNDS: {
    LIST: '/refunds/',
    DETAIL: (id: number | string) => `/refunds/${id}/`,
    APPROVE: (id: number | string) => `/refunds/${id}/approve/`,
    REJECT: (id: number | string) => `/refunds/${id}/reject/`,
  } as const,
  RENT_RECORDS: {
    LIST: '/rent-records/',
    DETAIL: (id: number | string) => `/rent-records/${id}/`,
    GENERATE: '/rent-records/generate/',
    HISTORY: (id: number | string) => `/rent-records/${id}/history/`,
    CALCULATE_LATE_FEE: '/rent-records/calculate-late-fee/',
    LATE_FEE_CONFIG: '/rent-records/late-fee-config/',
  } as const,
  STATUSES: {
    PENDING: 'pending',
    PAID: 'paid',
    PARTIALLY_PAID: 'partially_paid',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    REFUNDED: 'refunded',
    PROCESSING: 'processing',
    OVERDUE: 'overdue',
  } as const,
  STATUS_LABELS: {
    pending: 'Pending',
    paid: 'Paid',
    partially_paid: 'Partially Paid',
    failed: 'Failed',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    processing: 'Processing',
    overdue: 'Overdue',
  } as const,
  STATUS_CONFIG: {
    pending: {
      label: 'Pending',
      color: '#D97706',
      backgroundColor: '#FEF3C7',
      icon: 'clock-outline',
    },
    paid: {
      label: 'Paid',
      color: '#059669',
      backgroundColor: '#D1FAE5',
      icon: 'check-circle-outline',
    },
    partially_paid: {
      label: 'Partially Paid',
      color: '#2563EB',
      backgroundColor: '#DBEAFE',
      icon: 'clock-outline',
    },
    failed: {
      label: 'Failed',
      color: '#DC2626',
      backgroundColor: '#FEE2E2',
      icon: 'close-circle-outline',
    },
    cancelled: {
      label: 'Cancelled',
      color: '#6B7280',
      backgroundColor: '#F3F4F6',
      icon: 'cancel',
    },
    refunded: {
      label: 'Refunded',
      color: '#7C3AED',
      backgroundColor: '#EDE9FE',
      icon: 'refresh',
    },
    processing: {
      label: 'Processing',
      color: '#2563EB',
      backgroundColor: '#DBEAFE',
      icon: 'loading',
    },
    overdue: {
      label: 'Overdue',
      color: '#DC2626',
      backgroundColor: '#FEE2E2',
      icon: 'alert-circle-outline',
    },
  } as const,
  METHODS: {
    CASH: 'cash',
    BANK_TRANSFER: 'bank_transfer',
    UPI: 'upi',
    CHEQUE: 'cheque',
    CREDIT_CARD: 'credit_card',
    DEBIT_CARD: 'debit_card',
    WALLET: 'wallet',
    NET_BANKING: 'net_banking',
    OTHER: 'other',
  } as const,
  METHOD_LABELS: {
    cash: 'Cash',
    bank_transfer: 'Bank Transfer',
    upi: 'UPI',
    cheque: 'Cheque',
    credit_card: 'Credit Card',
    debit_card: 'Debit Card',
    wallet: 'Wallet',
    net_banking: 'Net Banking',
    other: 'Other',
  } as const,
  METHOD_CONFIG: {
    cash: { label: 'Cash', icon: 'cash', color: '#059669' },
    bank_transfer: { label: 'Bank Transfer', icon: 'bank', color: '#2563EB' },
    upi: { label: 'UPI', icon: 'cellphone', color: '#7C3AED' },
    cheque: { label: 'Cheque', icon: 'checkbook', color: '#D97706' },
    credit_card: { label: 'Credit Card', icon: 'credit-card', color: '#DC2626' },
    debit_card: { label: 'Debit Card', icon: 'credit-card-outline', color: '#0891B2' },
    wallet: { label: 'Wallet', icon: 'wallet', color: '#059669' },
    net_banking: { label: 'Net Banking', icon: 'web', color: '#4B5563' },
    other: { label: 'Other', icon: 'dots-horizontal', color: '#6B7280' },
  } as const,
  SORT_OPTIONS: {
    NEWEST: 'newest',
    OLDEST: 'oldest',
    AMOUNT_HIGH: 'amount_high',
    AMOUNT_LOW: 'amount_low',
    DUE_DATE: 'due_date',
    STATUS: 'status',
  } as const,
  SORT_LABELS: {
    newest: 'Newest',
    oldest: 'Oldest',
    amount_high: 'Amount: High to Low',
    amount_low: 'Amount: Low to High',
    due_date: 'Due Date',
    status: 'Status',
  } as const,
  INVOICE_STATUSES: {
    DRAFT: 'draft',
    SENT: 'sent',
    VIEWED: 'viewed',
    PAID: 'paid',
    OVERDUE: 'overdue',
    CANCELLED: 'cancelled',
  } as const,
  INVOICE_STATUS_LABELS: {
    draft: 'Draft',
    sent: 'Sent',
    viewed: 'Viewed',
    paid: 'Paid',
    overdue: 'Overdue',
    cancelled: 'Cancelled',
  } as const,
  INVOICE_STATUS_CONFIG: {
    draft: { label: 'Draft', color: '#6B7280', backgroundColor: '#F3F4F6' },
    sent: { label: 'Sent', color: '#2563EB', backgroundColor: '#DBEAFE' },
    viewed: { label: 'Viewed', color: '#7C3AED', backgroundColor: '#EDE9FE' },
    paid: { label: 'Paid', color: '#059669', backgroundColor: '#D1FAE5' },
    overdue: { label: 'Overdue', color: '#DC2626', backgroundColor: '#FEE2E2' },
    cancelled: { label: 'Cancelled', color: '#6B7280', backgroundColor: '#F3F4F6' },
  } as const,
  PAYOUT_STATUSES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    RETRYING: 'retrying',
  } as const,
  PAYOUT_STATUS_LABELS: {
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    retrying: 'Retrying',
  } as const,
  PAYOUT_STATUS_CONFIG: {
    pending: { label: 'Pending', color: '#D97706', backgroundColor: '#FEF3C7' },
    processing: { label: 'Processing', color: '#2563EB', backgroundColor: '#DBEAFE' },
    completed: { label: 'Completed', color: '#059669', backgroundColor: '#D1FAE5' },
    failed: { label: 'Failed', color: '#DC2626', backgroundColor: '#FEE2E2' },
    cancelled: { label: 'Cancelled', color: '#6B7280', backgroundColor: '#F3F4F6' },
    retrying: { label: 'Retrying', color: '#7C3AED', backgroundColor: '#EDE9FE' },
  } as const,
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
  } as const,
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 10 * 60 * 1000,
    ANALYTICS_STALE_TIME: 5 * 60 * 1000,
  } as const,
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Unable to connect to the server. Please check your internet connection.',
    UNAUTHORIZED: 'You are not authorized. Please log in again.',
    FORBIDDEN: 'You do not have permission to perform this action.',
    NOT_FOUND: 'Payment not found.',
    CONFLICT: 'This action conflicts with existing data.',
    VALIDATION_ERROR: 'Please check the entered data.',
    RATE_LIMITED: 'Too many requests. Please try again later.',
    SERVER_ERROR: 'Server error. Please try again later.',
    MAINTENANCE: 'The system is under maintenance. Please try again later.',
    SUBSCRIPTION_EXPIRED: 'Your subscription has expired. Please renew to continue.',
    PERMISSION_DENIED: 'You do not have permission to access this resource.',
    OFFLINE: 'You are offline. Some features may be unavailable.',
    LIMIT_REACHED: 'You have reached your plan limit. Please upgrade.',
    GENERIC: 'Something went wrong. Please try again.',
    PAYMENT_INIT_FAILED: 'Failed to initiate payment. Please try again.',
    PAYMENT_VERIFY_FAILED: 'Payment verification failed. Please contact support.',
    REFUND_FAILED: 'Failed to process refund. Please try again.',
    INVOICE_GENERATE_FAILED: 'Failed to generate invoice. Please try again.',
    PAYMENT_LINK_EXPIRED: 'This payment link has expired. Please request a new one.',
    PAYMENT_ALREADY_PAID: 'This payment has already been completed.',
    INSUFFICIENT_BALANCE: 'Insufficient balance to process refund.',
    MAX_RETRIES_REACHED: 'Maximum retry attempts reached for this payment.',
  } as const,
  EMPTY_STATE: {
    NO_PAYMENTS: {
      title: 'No payments found',
      description: 'Payments will appear here once rent records are generated.',
      actionLabel: 'Generate Rent Records',
    },
    NO_OVERDUE: {
      title: 'No overdue payments',
      description: 'All payments are up to date. Great job!',
    },
    NO_PENDING: {
      title: 'No pending payments',
      description: 'All payments have been processed.',
    },
    NO_FAILED: {
      title: 'No failed payments',
      description: 'All payments were processed successfully.',
    },
    NO_INVOICES: {
      title: 'No invoices found',
      description: 'Invoices will be generated automatically for rent records.',
    },
    NO_REFUNDS: {
      title: 'No refunds found',
      description: 'Refund requests will appear here.',
    },
    NO_ANALYTICS: {
      title: 'No analytics data',
      description: 'Analytics will be available once you have payment history.',
    },
    NO_RECEIPTS: {
      title: 'No receipts found',
      description: 'Receipts will be generated after payment.',
    },
  } as const,
  FEATURE_LIMITS: {
    PAYMENTS_PER_MONTH: 'payments_per_month',
    INVOICES_PER_MONTH: 'invoices_per_month',
    REFUNDS_PER_MONTH: 'refunds_per_month',
    REMINDERS_PER_MONTH: 'reminders_per_month',
    EXPORTS_PER_MONTH: 'exports_per_month',
  } as const,
} as const;

export const ERROR_MESSAGES = PAYMENT_CONSTANTS.ERROR_MESSAGES;
export const EMPTY_STATE = PAYMENT_CONSTANTS.EMPTY_STATE;
