export const MAINTENANCE_CONSTANTS = {
  API: {
    LIST: '/api/maintenance/',
    DETAIL: (id: number | string) => `/api/maintenance/${id}/`,
    CREATE: '/api/maintenance/',
    UPDATE: (id: number | string) => `/api/maintenance/${id}/`,
    DELETE: (id: number | string) => `/api/maintenance/${id}/`,
    DASHBOARD: '/api/maintenance/dashboard/',
    UPDATE_STATUS: (id: number | string) => `/api/maintenance/${id}/update-status/`,
    ASSIGN_CARETAKER: (id: number | string) => `/api/maintenance/${id}/assign-caretaker/`,
    ASSIGN_VENDOR: (id: number | string) => `/api/maintenance/${id}/assign-vendor/`,
    COMMENTS: (id: number | string) => `/api/maintenance/${id}/comments/`,
    EXPENSES: (id: number | string) => `/api/maintenance/${id}/expenses/`,
    PHOTOS: (id: number | string) => `/api/maintenance/${id}/photos/`,
    DOCUMENTS: (id: number | string) => `/api/maintenance/${id}/documents/`,
    TIMELINE: (id: number | string) => `/api/maintenance/${id}/timeline/`,
    RESOLVED: '/api/maintenance/resolved/',
    CLOSED: '/api/maintenance/closed/',
    VENDORS: '/api/vendors/',
    VENDOR_DETAIL: (id: number | string) => `/api/vendors/${id}/`,
    UNIT_DOCUMENTS: '/api/unit-all-documents/',
    UNIT_IMAGES: '/api/unit-images/',
  } as const,
  STATUS: {
    CREATED: 'created',
    SUBMITTED: 'submitted',
    ACKNOWLEDGED: 'acknowledged',
    ASSIGNED: 'assigned',
    IN_PROGRESS: 'in_progress',
    WAITING_FOR_PARTS: 'waiting_for_parts',
    WAITING_FOR_APPROVAL: 'waiting_for_approval',
    RESOLVED: 'resolved',
    CLOSED: 'closed',
    REJECTED: 'rejected',
    CANCELLED: 'cancelled',
  } as const,
  STATUS_LABELS: {
    created: 'Created',
    submitted: 'Submitted',
    acknowledged: 'Acknowledged',
    assigned: 'Assigned',
    in_progress: 'In Progress',
    waiting_for_parts: 'Waiting for Parts',
    waiting_for_approval: 'Waiting for Approval',
    resolved: 'Resolved',
    closed: 'Closed',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
  } as const,
  STATUS_CONFIG: {
    created: { label: 'Created', color: '#6b7280', backgroundColor: '#f3f4f6' },
    submitted: { label: 'Submitted', color: '#3b82f6', backgroundColor: '#dbeafe' },
    acknowledged: { label: 'Acknowledged', color: '#8b5cf6', backgroundColor: '#ede9fe' },
    assigned: { label: 'Assigned', color: '#f59e0b', backgroundColor: '#fef3c7' },
    in_progress: { label: 'In Progress', color: '#f97316', backgroundColor: '#ffedd5' },
    waiting_for_parts: { label: 'Waiting for Parts', color: '#6b7280', backgroundColor: '#f3f4f6' },
    waiting_for_approval: { label: 'Waiting for Approval', color: '#eab308', backgroundColor: '#fef9c3' },
    resolved: { label: 'Resolved', color: '#10b981', backgroundColor: '#d1fae5' },
    closed: { label: 'Closed', color: '#059669', backgroundColor: '#d1fae5' },
    rejected: { label: 'Rejected', color: '#ef4444', backgroundColor: '#fee2e2' },
    cancelled: { label: 'Cancelled', color: '#9ca3af', backgroundColor: '#f3f4f6' },
  } as const,
  PRIORITY: {
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    URGENT: 'urgent',
  } as const,
  PRIORITY_LABELS: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
  } as const,
  PRIORITY_CONFIG: {
    low: { label: 'Low', color: '#10b981', backgroundColor: '#d1fae5' },
    medium: { label: 'Medium', color: '#f59e0b', backgroundColor: '#fef3c7' },
    high: { label: 'High', color: '#f97316', backgroundColor: '#ffedd5' },
    urgent: { label: 'Urgent', color: '#ef4444', backgroundColor: '#fee2e2' },
  } as const,
  CATEGORY: {
    PLUMBING: 'plumbing',
    ELECTRICAL: 'electrical',
    AC: 'ac',
    APPLIANCE: 'appliance',
    CARPENTRY: 'carpentry',
    CLEANING: 'cleaning',
    SECURITY: 'security',
    WATER: 'water',
    INTERNET: 'internet',
    OTHER: 'other',
  } as const,
  CATEGORY_LABELS: {
    plumbing: 'Plumbing',
    electrical: 'Electrical',
    ac: 'AC',
    appliance: 'Appliance',
    carpentry: 'Carpentry',
    cleaning: 'Cleaning',
    security: 'Security',
    water: 'Water',
    internet: 'Internet',
    other: 'Other',
  } as const,
  CATEGORY_ICONS: {
    plumbing: '🚰',
    electrical: '⚡',
    ac: '❄️',
    appliance: '🔌',
    carpentry: '🔨',
    cleaning: '🧹',
    security: '🔒',
    water: '💧',
    internet: '📶',
    other: '📋',
  } as const,
  DOCUMENT_TYPE: {
    BEFORE_PHOTO: 'before_photo',
    AFTER_PHOTO: 'after_photo',
    INVOICE: 'invoice',
    RECEIPT: 'receipt',
    SERVICE_REPORT: 'service_report',
    OTHER: 'other',
  } as const,
  DOCUMENT_TYPE_LABELS: {
    before_photo: 'Before Photo',
    after_photo: 'After Photo',
    invoice: 'Invoice',
    receipt: 'Receipt',
    service_report: 'Service Report',
    other: 'Other Document',
  } as const,
  ACTIVITY_TYPE: {
    CREATED: 'created',
    UPDATED: 'updated',
    ASSIGNED: 'assigned',
    STATUS_CHANGED: 'status_changed',
    COMMENT_ADDED: 'comment_added',
    PHOTO_UPLOADED: 'photo_uploaded',
    DOCUMENT_UPLOADED: 'document_uploaded',
    EXPENSE_ADDED: 'expense_added',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    RESOLVED: 'resolved',
    CLOSED: 'closed',
  } as const,
  ACTIVITY_TYPE_LABELS: {
    created: 'Request Created',
    updated: 'Request Updated',
    assigned: 'Assigned',
    status_changed: 'Status Changed',
    comment_added: 'Comment Added',
    photo_uploaded: 'Photo Uploaded',
    document_uploaded: 'Document Uploaded',
    expense_added: 'Expense Added',
    approved: 'Approved',
    rejected: 'Rejected',
    resolved: 'Resolved',
    closed: 'Closed',
  } as const,
  PAYMENT_STATUS: {
    PENDING: 'pending',
    PAID: 'paid',
    PARTIALLY_PAID: 'partially_paid',
    REFUNDED: 'refunded',
  } as const,
  PAYMENT_STATUS_LABELS: {
    pending: 'Pending',
    paid: 'Paid',
    partially_paid: 'Partially Paid',
    refunded: 'Refunded',
  } as const,
  PAYMENT_STATUS_CONFIG: {
    pending: { label: 'Pending', color: '#f59e0b', backgroundColor: '#fef3c7' },
    paid: { label: 'Paid', color: '#10b981', backgroundColor: '#d1fae5' },
    partially_paid: { label: 'Partially Paid', color: '#f97316', backgroundColor: '#ffedd5' },
    refunded: { label: 'Refunded', color: '#6b7280', backgroundColor: '#f3f4f6' },
  } as const,
  SORT_OPTIONS: {
    newest: 'newest',
    oldest: 'oldest',
    priority: 'priority',
    status: 'status',
    updated: 'updated',
  } as const,
  SORT_LABELS: {
    newest: 'Newest First',
    oldest: 'Oldest First',
    priority: 'Priority',
    status: 'Status',
    updated: 'Last Updated',
  } as const,
  FILTERS: {
    STATUS: 'status',
    PRIORITY: 'priority',
    CATEGORY: 'category',
    BUILDING: 'building',
    UNIT: 'unit',
    RENTER: 'renter',
    CARETAKER: 'caretaker',
    VENDOR: 'vendor',
    DATE_FROM: 'date_from',
    DATE_TO: 'date_to',
    SEARCH: 'search',
  } as const,
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    PAGE_SIZE_OPTIONS: [10, 20, 50],
  } as const,
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 10 * 60 * 1000,
  } as const,
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Unable to connect to the server. Please check your internet connection.',
    UNAUTHORIZED: 'You are not authorized. Please log in again.',
    FORBIDDEN: 'You do not have permission to perform this action.',
    NOT_FOUND: 'Maintenance request not found.',
    CONFLICT: 'This action conflicts with existing data.',
    VALIDATION_ERROR: 'Please check the entered data.',
    RATE_LIMITED: 'Too many requests. Please try again later.',
    SERVER_ERROR: 'Server error. Please try again later.',
    MAINTENANCE: 'The system is under maintenance. Please try again later.',
    SUBSCRIPTION_EXPIRED: 'Your subscription has expired. Please renew to continue.',
    PERMISSION_DENIED: 'You do not have permission to access this resource.',
    OFFLINE: 'You are offline. Some features may be unavailable.',
    LIMIT_REACHED: 'You have reached your maintenance request limit. Please upgrade.',
    GENERIC: 'Something went wrong. Please try again.',
    DELETE_CONFIRM: 'Are you sure you want to delete this maintenance request? This action cannot be undone.',
    CANCEL_CONFIRM: 'Are you sure you want to cancel this maintenance request?',
  } as const,
  EMPTY_STATE: {
    TITLE: 'No maintenance requests found',
    DESCRIPTION: 'Get started by creating your first maintenance request.',
    ACTION_LABEL: 'Create Request',
  } as const,
  DASHBOARD: {
    TITLE: 'Maintenance Dashboard',
    OPEN_REQUESTS: 'Open Requests',
    IN_PROGRESS: 'In Progress',
    RESOLVED: 'Resolved',
    CLOSED: 'Closed',
    URGENT: 'Urgent',
    TOTAL_EXPENSES: 'Total Expenses',
    PENDING_APPROVAL: 'Pending Approval',
  } as const,
} as const;

export type MaintenanceConstants = typeof MAINTENANCE_CONSTANTS;
