export const Colors = {
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primaryLight: '#3B82F6',
  secondary: '#10B981',
  secondaryDark: '#059669',
  secondaryLight: '#34D399',
  accent: '#8B5CF6',
  accentLight: '#A78BFA',
  background: '#F9FAFB',
  surface: '#FFFFFF',
  surfaceElevated: '#FFFFFF',
  text: '#111827',
  textSecondary: '#6B7280',
  textTertiary: '#9CA3AF',
  textInverse: '#FFFFFF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  info: '#3B82F6',
  overlay: 'rgba(0, 0, 0, 0.5)',
  skeleton: '#E5E7EB',
  skeletonShine: '#F9FAFB',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  gray700: '#374151',
  gray800: '#1F2937',
  gray900: '#111827',
  darkBackground: '#0F172A',
  darkSurface: '#1E293B',
  darkSurfaceElevated: '#334155',
  darkText: '#F8FAFC',
  darkTextSecondary: '#94A3B8',
  darkBorder: '#334155',
  darkBorderLight: '#475569',
} as const;

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  huge: 48,
  massive: 64,
} as const;

export const Radius = {
  xs: 4,
  sm: 6,
  md: 8,
  lg: 12,
  xl: 16,
  xxl: 20,
  full: 9999,
} as const;

export const FontSizes = {
  xs: 11,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 18,
  xxl: 20,
  xxxl: 24,
  huge: 32,
  massive: 48,
} as const;

export const FontWeights = {
  light: '300' as const,
  regular: '400' as const,
  medium: '500' as const,
  semibold: '600' as const,
  bold: '700' as const,
  extrabold: '800' as const,
} as const;

export const Shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  xl: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
} as const;

export const Animations = {
  duration: {
    fast: 150,
    normal: 250,
    slow: 350,
  },
  easing: {
    easeIn: 'ease-in',
    easeOut: 'ease-out',
    easeInOut: 'ease-in-out',
  },
} as const;

export const Icons = {
  home: 'home',
  dashboard: 'dashboard',
  property: 'business',
  building: 'apartment',
  unit: 'meeting-room',
  renter: 'person',
  caretaker: 'supervised-user-circle',
  agreement: 'description',
  payment: 'payment',
  subscription: 'card-membership',
  notification: 'notifications',
  report: 'assessment',
  profile: 'account-circle',
  settings: 'settings',
  logout: 'logout',
  back: 'arrow-back',
  forward: 'arrow-forward',
  add: 'add',
  edit: 'edit',
  delete: 'delete',
  search: 'search',
  filter: 'filter',
  sort: 'sort',
  menu: 'menu',
  close: 'close',
  check: 'check',
  error: 'error',
  warning: 'warning',
  info: 'info',
  success: 'check-circle',
  loading: 'cached',
  empty: 'inbox',
  calendar: 'calendar-today',
  clock: 'access-time',
  location: 'location-on',
  phone: 'phone',
  email: 'email',
  camera: 'camera-alt',
  image: 'image',
  document: 'description',
  download: 'download',
  upload: 'upload',
  share: 'share',
  favorite: 'favorite',
  star: 'star',
  lock: 'lock',
  unlock: 'lock-open',
  visibility: 'visibility',
  visibilityOff: 'visibility-off',
  more: 'more-horiz',
  refresh: 'refresh',
  arrowUp: 'arrow-upward',
  arrowDown: 'arrow-downward',
} as const;

export const MaxContentWidth = 800;
export const BottomTabInset = 80;
