import type { VisitorStatus } from "../types/visitors";

export type VisitorConstants = typeof VISITOR_CONSTANTS;

export const VISITOR_CONSTANTS = {
  API: {
    LIST: "/api/visitors/",
    DETAIL: (id: number | string) => `/api/visitors/${id}/`,
    CREATE: "/api/visitors/",
    UPDATE: (id: number | string) => `/api/visitors/${id}/`,
    DELETE: (id: number | string) => `/api/visitors/${id}/`,
    APPROVE: (id: number | string) => `/api/visitors/${id}/approve/`,
    REJECT: (id: number | string) => `/api/visitors/${id}/reject/`,
    CANCEL: (id: number | string) => `/api/visitors/${id}/cancel/`,
    BLOCK: (id: number | string) => `/api/visitors/${id}/block/`,
    CHECK_IN: (id: number | string) => `/api/visitors/${id}/check-in/`,
    CHECK_OUT: (id: number | string) => `/api/visitors/${id}/check-out/`,
    GENERATE_QR: (id: number | string) => `/api/visitors/${id}/generate-qr/`,
    VERIFY_QR: (id: number | string) => `/api/visitors/${id}/verify-qr/`,
    GENERATE_OTP: (id: number | string) => `/api/visitors/${id}/generate-otp/`,
    VERIFY_OTP: (id: number | string) => `/api/visitors/${id}/verify-otp/`,
    HISTORY: (id: number | string) => `/api/visitors/${id}/history/`,
    STATS: "/api/visitors/stats/",
    PUBLIC_VERIFY_QR: "/api/visitors/verify/verify-qr/",
    MARK_EXPIRED: "/api/visitors/mark-expired/",
    NOTIFICATIONS: "/api/notifications/get/",
    BUILDINGS: "/api/buildings/",
    UNITS: "/api/units/",
    RENTERS: "/renters/",
  } as const,
  STATUS: {
    REQUESTED: "requested" as VisitorStatus,
    PENDING_APPROVAL: "pending_approval" as VisitorStatus,
    APPROVED: "approved" as VisitorStatus,
    REJECTED: "rejected" as VisitorStatus,
    CHECKED_IN: "checked_in" as VisitorStatus,
    CHECKED_OUT: "checked_out" as VisitorStatus,
    EXPIRED: "expired" as VisitorStatus,
    CANCELLED: "cancelled" as VisitorStatus,
    BLOCKED: "blocked" as VisitorStatus,
  } as const,
  STATUS_LABELS: {
    requested: "Requested",
    pending_approval: "Pending Approval",
    approved: "Approved",
    rejected: "Rejected",
    checked_in: "Checked In",
    checked_out: "Checked Out",
    expired: "Expired",
    cancelled: "Cancelled",
    blocked: "Blocked",
  } as const,
  STATUS_CONFIG: {
    requested: {
      label: "Requested",
      color: "#6b7280",
      backgroundColor: "#f3f4f6",
      icon: "📋",
    },
    pending_approval: {
      label: "Pending Approval",
      color: "#f59e0b",
      backgroundColor: "#fef3c7",
      icon: "⏳",
    },
    approved: {
      label: "Approved",
      color: "#10b981",
      backgroundColor: "#d1fae5",
      icon: "✅",
    },
    rejected: {
      label: "Rejected",
      color: "#ef4444",
      backgroundColor: "#fee2e2",
      icon: "❌",
    },
    checked_in: {
      label: "Checked In",
      color: "#3b82f6",
      backgroundColor: "#dbeafe",
      icon: "🚪",
    },
    checked_out: {
      label: "Checked Out",
      color: "#8b5cf6",
      backgroundColor: "#ede9fe",
      icon: "🚶",
    },
    expired: {
      label: "Expired",
      color: "#6b7280",
      backgroundColor: "#f3f4f6",
      icon: "⏰",
    },
    cancelled: {
      label: "Cancelled",
      color: "#9ca3af",
      backgroundColor: "#f9fafb",
      icon: "🚫",
    },
    blocked: {
      label: "Blocked",
      color: "#dc2626",
      backgroundColor: "#fef2f2",
      icon: "🚫",
    },
  } as const,
  PURPOSE: {
    PERSONAL_VISIT: "personal_visit",
    FAMILY_VISIT: "family_visit",
    BUSINESS_MEETING: "business_meeting",
    SERVICE_PERSONNEL: "service_personnel",
    MAINTENANCE: "maintenance",
    DELIVERY: "delivery",
    EMERGENCY: "emergency",
    OTHER: "other",
  } as const,
  PURPOSE_LABELS: {
    personal_visit: "Personal Visit",
    family_visit: "Family Visit",
    business_meeting: "Business Meeting",
    service_personnel: "Service Personnel",
    maintenance: "Maintenance / Repair",
    delivery: "Delivery / Courier",
    emergency: "Emergency",
    other: "Other",
  } as const,
  OTP: {
    LENGTH: 6,
    MAX_ATTEMPTS: 5,
    EXPIRY_MINUTES: 5,
    RESEND_COOLDOWN_SECONDS: 60,
  } as const,
  QR: {
    MAX_USES_DEFAULT: 1,
    DEFAULT_EXPIRY_HOURS: 24,
  } as const,
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    PAGE_SIZE_OPTIONS: [10, 20, 50],
  } as const,
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 10 * 60 * 1000,
  } as const,
  SORT_OPTIONS: {
    newest: "newest",
    oldest: "oldest",
    visit_date_asc: "visit_date",
    visit_date_desc: "-visit_date",
    name_asc: "visitor_name",
    name_desc: "-visitor_name",
    status: "status",
  } as const,
  SORT_LABELS: {
    newest: "Newest First",
    oldest: "Oldest First",
    visit_date_asc: "Visit Date (Earliest)",
    visit_date_desc: "Visit Date (Latest)",
    name_asc: "Name (A-Z)",
    name_desc: "Name (Z-A)",
    status: "Status",
  } as const,
  FILTERS: {
    STATUS: "status",
    BUILDING: "building",
    UNIT: "unit",
    RENTER: "renter",
    PURPOSE: "purpose",
    DATE_RANGE: "date_range",
    SEARCH: "search",
  } as const,
  ERROR_MESSAGES: {
    NETWORK_ERROR: "Unable to connect to the server. Please check your internet connection.",
    UNAUTHORIZED: "You are not authorized. Please log in again.",
    FORBIDDEN: "You do not have permission to perform this action.",
    NOT_FOUND: "Visitor not found.",
    CONFLICT: "This action conflicts with existing data.",
    VALIDATION_ERROR: "Please check the entered data.",
    RATE_LIMITED: "Too many requests. Please try again later.",
    SERVER_ERROR: "Server error. Please try again later.",
    MAINTENANCE: "The system is under maintenance. Please try again later.",
    SUBSCRIPTION_EXPIRED: "Your subscription has expired. Please renew to continue.",
    PERMISSION_DENIED: "You do not have permission to access this resource.",
    OFFLINE: "You are offline. Some features may be unavailable.",
    LIMIT_REACHED: "You have reached your visitor limit. Please upgrade.",
    GENERIC: "Something went wrong. Please try again.",
    VISITOR_ALREADY_CHECKED_IN: "Visitor is already checked in.",
    VISITOR_ALREADY_CHECKED_OUT: "Visitor is already checked out.",
    VISITOR_NOT_APPROVED: "Visitor has not been approved yet.",
    INVALID_QR: "Invalid QR code.",
    EXPIRED_QR: "QR code has expired.",
    INVALID_OTP: "Invalid OTP code.",
    EXPIRED_OTP: "OTP has expired. Please request a new one.",
    MAX_OTP_ATTEMPTS: "Maximum OTP attempts exceeded. Please request a new OTP.",
    VISITOR_EXPIRED: "Visit has expired.",
    DELETE_CONFIRM: "Are you sure you want to delete this visitor request?",
    CANCEL_CONFIRM: "Are you sure you want to cancel this visitor request?",
    BLOCK_CONFIRM: "Are you sure you want to block this visitor?",
    CHECK_IN_CONFIRM: "Confirm check-in for this visitor?",
    CHECK_OUT_CONFIRM: "Confirm check-out for this visitor?",
    REJECT_CONFIRM: "Are you sure you want to reject this visitor request?",
  } as const,
  EMPTY_STATE: {
    TITLE: "No visitors found",
    DESCRIPTION: "Get started by creating your first visitor request.",
    ACTION_LABEL: "Create Visitor Request",
  } as const,
  EMPTY_HISTORY_TITLE: "No history yet",
  EMPTY_HISTORY_DESCRIPTION: "Activity history will appear here.",
  FEATURE_LIMIT_KEY: "max_visitors",
} as const;
