export const SLOW_REQUEST_THRESHOLD_MS = 5000;
export const VERY_SLOW_REQUEST_THRESHOLD_MS = 15000;
export const SLOW_UPLOAD_THRESHOLD_MS = 30000;
export const SLOW_DOWNLOAD_THRESHOLD_MS = 30000;
export const SCREEN_LOAD_THRESHOLD_MS = 2000;
export const APP_STARTUP_THRESHOLD_MS = 5000;
export const NAVIGATION_THRESHOLD_MS = 500;
