import { environment } from '@/config/environment';

export const API_ENDPOINTS = {
  AUTH: {
    SEND_OTP: '/auth/send-otp/',
    VERIFY_OTP_OWNER: '/auth/owner/verify-otp/',
    VERIFY_OTP_RENTER: '/auth/renter/verify-otp/',
    LOGIN: '/auth/login/',
    REGISTER: '/auth/register/',
    SOCIAL_AUTH: '/auth/social/',
    REFRESH_TOKEN: '/api/token/refresh/',
    LOGOUT: '/auth/logout/',
    LOGOUT_ALL: '/auth/logout-all/',
    PROFILE: '/auth/profile/',
    CHANGE_PASSWORD: '/change-password/',
    FORGOT_PASSWORD: '/forgot-password/',
    RESET_PASSWORD: '/reset-password/',
    BIOMETRIC_SETUP: '/auth/biometric/setup/',
    BIOMETRIC_DISABLE: '/auth/biometric/disable/',
    DEVICE_REGISTER: '/auth/device/register/',
    APP_VERSION: '/auth/app/version/',
    MAINTENANCE: '/auth/maintenance/',
  },
  DASHBOARD: {
    STATS: '/dashboard/stats/',
    ACTIVITY: '/dashboard/activity/',
    RECENT_RENT: '/dashboard/recent-rent/',
    RECENT_PAYMENTS: '/dashboard/recent-payments/',
    RECENT_MAINTENANCE: '/dashboard/recent-maintenance/',
    OWNER_SUMMARY: '/properties/owner/dashboard/',
    OWNER_DASHBOARD_SUMMARY: '/properties/owner/dashboard-summary/',
    UNIT_ANALYTICS: '/properties/unit_analytics',
    POLICE_VERIFICATION_STATS: '/police-verifications/dashboard_stats/',
  },
  PROPERTIES: {
    LIST: '/properties/',
    DETAIL: (id: string) => `/properties/${id}/`,
    CREATE: '/properties/',
    UPDATE: (id: string) => `/properties/${id}/`,
    DELETE: (id: string) => `/properties/${id}/`,
    STATS: (id: string) => `/properties/${id}/stats/`,
    DOCUMENTS: (id: string) => `/properties/${id}/documents/`,
  },
  BUILDINGS: {
    LIST: '/api/buildings/',
    DETAIL: (id: string) => `/api/buildings/${id}/`,
    CREATE: '/api/buildings/',
    UPDATE: (id: string) => `/api/buildings/${id}/`,
    DELETE: (id: string) => `/api/buildings/${id}/`,
  },
  UNITS: {
    LIST: (buildingId: string) => `/buildings/${buildingId}/units/`,
    DETAIL: (id: string) => `/units/${id}/`,
    CREATE: (buildingId: string) => `/buildings/${buildingId}/units/`,
    UPDATE: (id: string) => `/units/${id}/`,
    DELETE: (id: string) => `/units/${id}/`,
    BULK_UPDATE: (buildingId: string) => `/buildings/${buildingId}/units/bulk/`,
  },
  RENTERS: {
    LIST: '/renters/',
    DETAIL: (id: string) => `/renters/${id}/`,
    CREATE: '/renters/',
    UPDATE: (id: string) => `/renters/${id}/`,
    DELETE: (id: string) => `/renters/${id}/`,
    VERIFY: (id: string) => `/renters/${id}/verify/`,
    BLACKLIST: (id: string) => `/renters/${id}/blacklist/`,
    HISTORY: (id: string) => `/renters/${id}/history/`,
  },
  CARETAKERS: {
    LIST: '/caretakers/',
    DETAIL: (id: string) => `/caretakers/${id}/`,
    CREATE: '/caretakers/',
    UPDATE: (id: string) => `/caretakers/${id}/`,
    DELETE: (id: string) => `/caretakers/${id}/`,
    ASSIGN_BUILDING: (id: string) => `/caretakers/${id}/assign-building/`,
    REMOVE_BUILDING: (id: string) => `/caretakers/${id}/remove-building/`,
  },
  VISITORS: {
    LIST: '/api/visitors/',
    DETAIL: (id: string) => `/api/visitors/${id}/`,
    CREATE: '/api/visitors/',
    UPDATE: (id: string) => `/api/visitors/${id}/`,
    DELETE: (id: string) => `/api/visitors/${id}/`,
    APPROVE: (id: string) => `/api/visitors/${id}/approve/`,
    REJECT: (id: string) => `/api/visitors/${id}/reject/`,
    CANCEL: (id: string) => `/api/visitors/${id}/cancel/`,
    BLOCK: (id: string) => `/api/visitors/${id}/block/`,
    CHECK_IN: (id: string) => `/api/visitors/${id}/check-in/`,
    CHECK_OUT: (id: string) => `/api/visitors/${id}/check-out/`,
    GENERATE_QR: (id: string) => `/api/visitors/${id}/generate-qr/`,
    VERIFY_QR: (id: string) => `/api/visitors/${id}/verify-qr/`,
    GENERATE_OTP: (id: string) => `/api/visitors/${id}/generate-otp/`,
    VERIFY_OTP: (id: string) => `/api/visitors/${id}/verify-otp/`,
    HISTORY: (id: string) => `/api/visitors/${id}/history/`,
    STATS: '/api/visitors/stats/',
    PUBLIC_VERIFY_QR: '/api/visitors/verify/verify-qr/',
    MARK_EXPIRED: '/api/visitors/mark-expired/',
    BUILDINGS: '/api/buildings/',
    UNITS: '/api/units/',
    RENTERS: '/renters/',
    NOTIFICATIONS: '/api/notifications/get/',
  },
  RENT_RECORDS: {
    LIST: '/rent-records/',
    DETAIL: (id: string) => `/rent-records/${id}/`,
    CREATE: '/rent-records/',
    UPDATE: (id: string) => `/rent-records/${id}/`,
    DELETE: (id: string) => `/rent-records/${id}/`,
    GENERATE: '/rent-records/generate/',
    HISTORY: (id: string) => `/rent-records/${id}/history/`,
  },
  PAYMENTS: {
    LIST: '/payments/',
    DETAIL: (id: string) => `/payments/${id}/`,
    CREATE: '/payments/',
    UPDATE: (id: string) => `/payments/${id}/`,
    DELETE: (id: string) => `/payments/${id}/`,
    INITIATE: '/payments/initiate/',
    VERIFY: '/payments/verify/',
    REFUND: (id: string) => `/payments/${id}/refund/`,
    HISTORY: '/payments/history/',
  },
  INVOICES: {
    LIST: '/invoices/',
    DETAIL: (id: string) => `/invoices/${id}/`,
    CREATE: '/invoices/',
    UPDATE: (id: string) => `/invoices/${id}/`,
    DELETE: (id: string) => `/invoices/${id}/`,
    DOWNLOAD: (id: string) => `/invoices/${id}/download/`,
    SEND: (id: string) => `/invoices/${id}/send/`,
    MARK_PAID: (id: string) => `/invoices/${id}/mark-paid/`,
  },
  AGREEMENTS: {
    LIST: '/agreements/',
    DETAIL: (id: string) => `/agreements/${id}/`,
    CREATE: '/agreements/',
    UPDATE: (id: string) => `/agreements/${id}/`,
    DELETE: (id: string) => `/agreements/${id}/`,
    UPLOAD: (id: string) => `/agreements/${id}/upload/`,
    DOWNLOAD: (id: string) => `/agreements/${id}/download/`,
    SIGN: (id: string) => `/agreements/${id}/sign/`,
    TERMINATE: (id: string) => `/agreements/${id}/terminate/`,
    TEMPLATES: '/agreements/templates/',
  },
  SUBSCRIPTIONS: {
    CURRENT: '/subscriptions/current/',
    PLANS: '/subscriptions/plans/',
    UPGRADE: '/subscriptions/upgrade/',
    CANCEL: '/subscriptions/cancel/',
    HISTORY: '/subscriptions/history/',
    INVOICES: '/subscriptions/invoices/',
  },
  ADD_ONS: {
    LIST: '/add-ons/',
    PURCHASE: '/add-ons/purchase/',
    USAGE: '/add-ons/usage/',
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    UNREAD: '/notifications/unread/',
    MARK_READ: (id: string) => `/notifications/${id}/mark-read/`,
    MARK_ALL_READ: '/notifications/mark-all-read/',
    DELETE: (id: string) => `/notifications/${id}/`,
    SETTINGS: '/notifications/settings/',
  },
  REPORTS: {
    FINANCIAL: '/reports/financial/',
    OCCUPANCY: '/reports/occupancy/',
    PAYMENT: '/reports/payment/',
    RENTER: '/reports/renter/',
    MAINTENANCE: '/reports/maintenance/',
    EXPORT: '/reports/export/',
  },
  CA_PARTNERS: {
    LIST: '/ca-partners/',
    DETAIL: (id: string) => `/ca-partners/${id}/`,
    ASSIGN: '/ca-partners/assign/',
    CLIENTS: (id: string) => `/ca-partners/${id}/clients/`,
  },
  SUPPORT: {
    TICKETS: '/support/tickets/',
    TICKET_DETAIL: (id: string) => `/support/tickets/${id}/`,
    CREATE_TICKET: '/support/tickets/',
    UPDATE_TICKET: (id: string) => `/support/tickets/${id}/`,
    CHAT: (id: string) => `/support/tickets/${id}/chat/`,
    FAQ: '/support/faq/',
    CONTACT: '/support/contact/',
  },
  SETTINGS: {
    PROFILE: '/settings/profile/',
    PREFERENCES: '/settings/preferences/',
    SECURITY: '/settings/security/',
    NOTIFICATIONS: '/settings/notifications/',
    BILLING: '/settings/billing/',
    TEAM: '/settings/team/',
    ROLES: '/settings/roles/',
  },
  UPLOAD: {
    IMAGE: '/upload/image/',
    VIDEO: '/upload/video/',
    DOCUMENT: '/upload/document/',
    CHUNK_INIT: '/upload/chunk/init/',
    CHUNK_UPLOAD: '/upload/chunk/upload/',
    CHUNK_COMPLETE: '/upload/chunk/complete/',
  },
  DOWNLOAD: {
    INVOICE: (id: string) => `/download/invoice/${id}/`,
    AGREEMENT: (id: string) => `/download/agreement/${id}/`,
    POLICE_VERIFICATION: (id: string) => `/download/police-verification/${id}/`,
    REPORT: (id: string) => `/download/report/${id}/`,
    BULK: '/download/bulk/',
  },
  DOCUMENTS: {
    LIST: '/api/documents/',
    DETAIL: (id: string | number) => `/api/documents/${id}/`,
    CREATE: '/api/documents/',
    UPDATE: (id: string | number) => `/api/documents/${id}/`,
    DELETE: (id: string | number) => `/api/documents/${id}/`,
    DOWNLOAD: (id: string | number) => `/api/documents/${id}/download/`,
    PREVIEW: (id: string | number) => `/api/documents/${id}/preview/`,
    UPLOAD: '/api/documents/upload/',
    MOVE: (id: string | number) => `/api/documents/${id}/move/`,
    COPY: (id: string | number) => `/api/documents/${id}/copy/`,
    SHARE: (id: string | number) => `/api/documents/${id}/share/`,
    FAVORITE: (id: string | number) => `/api/documents/${id}/favorite/`,
    ARCHIVE: (id: string | number) => `/api/documents/${id}/archive/`,
    RESTORE: (id: string | number) => `/api/documents/${id}/restore/`,
    VERSIONS: (id: string | number) => `/api/documents/${id}/versions/`,
    DUPLICATES: '/api/documents/duplicates/',
    FOLDERS: '/api/documents/folders/',
    USAGE_LIMITS: '/api/documents/usage-limits/',
    BULK_DELETE: '/api/documents/bulk-delete/',
    BULK_MOVE: '/api/documents/bulk-move/',
    BULK_DOWNLOAD: '/api/documents/bulk-download/',
    SEARCH: '/api/documents/search/',
    METADATA: (id: string | number) => `/api/documents/${id}/metadata/`,
  },
};

export const API_CONFIG = {
  BASE_URL: environment.apiUrl,
  TIMEOUT: environment.apiTimeout,
  RETRY_COUNT: environment.apiRetryCount,
  RETRY_DELAY: 1000,
  MAX_RETRY_DELAY: 10000,
  REFRESH_TOKEN_URL: '/api/token/refresh/',
  CORRELATION_ID_HEADER: 'X-Correlation-ID',
  DEVICE_ID_HEADER: 'X-Device-ID',
  APP_VERSION_HEADER: 'X-App-Version',
  PLATFORM_HEADER: 'X-Platform',
  LANGUAGE_HEADER: 'X-Language',
  TIMEZONE_HEADER: 'X-Timezone',
  AUTHORIZATION_HEADER: 'Authorization',
  BEARER_PREFIX: 'Bearer ',
  CONTENT_TYPE_JSON: 'application/json',
  CONTENT_TYPE_MULTIPART: 'multipart/form-data',
  ACCEPT_HEADER: 'application/json',
  CACHE_KEY_PREFIX: 'api_cache_',
  QUEUE_STORAGE_KEY: 'request_queue',
  NETWORK_TIMEOUT: 5000,
  SLOW_NETWORK_THRESHOLD: 3000,
};
