import type { CachePolicy, OperationCategory } from '../types';

export const NETWORK_STATES = {
  ONLINE: 'online',
  OFFLINE: 'offline',
  RECONNECTING: 'reconnecting',
  UNKNOWN: 'unknown',
} as const;

export const QUEUE_STATUS = {
  PENDING: 'pending',
  SYNCING: 'syncing',
  SUCCESS: 'success',
  FAILED: 'failed',
  CONFLICT: 'conflict',
} as const;

export const SYNC_STATUS = {
  IDLE: 'idle',
  SYNCING: 'syncing',
  SUCCESS: 'success',
  FAILED: 'failed',
  CONFLICT: 'conflict',
} as const;

export const CACHE_FRESHNESS = {
  FRESH: 'fresh',
  STALE: 'stale',
  OFFLINE_CACHED: 'offline-cached',
  UNAVAILABLE: 'unavailable',
} as const;

export const MAX_QUEUE_RETRIES = 3;
export const MAX_SYNC_RETRIES = 2;
export const QUEUE_RETRY_DELAY_MS = 2000;
export const SYNC_RETRY_DELAY_MS = 3000;

export const DEFAULT_CACHE_POLICIES: Record<string, CachePolicy> = {
  dashboard: {
    staleTime: 60_000,
    cacheTime: 5 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: false,
  },
  buildings: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  units: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  renters: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  caretakers: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  maintenance: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  notifications: {
    staleTime: 30_000,
    cacheTime: 5 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  recentRentRecords: {
    staleTime: 30_000,
    cacheTime: 5 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  rentRecords: {
    staleTime: 30_000,
    cacheTime: 5 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  payments: {
    staleTime: 15_000,
    cacheTime: 2 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  payouts: {
    staleTime: 15_000,
    cacheTime: 2 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  invoices: {
    staleTime: 30_000,
    cacheTime: 5 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  subscriptions: {
    staleTime: 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: true,
  },
  agreements: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  visitors: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  documents: {
    staleTime: 5 * 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: true,
    financialSensitive: false,
  },
  reports: {
    staleTime: 60_000,
    cacheTime: 10 * 60_000,
    freshnessLevel: 'stale',
    requiresAuth: true,
    financialSensitive: false,
  },
  subscriptionPlans: {
    staleTime: 60 * 60_000,
    cacheTime: 24 * 60 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: false,
    financialSensitive: false,
  },
  appVersion: {
    staleTime: 60 * 60_000,
    cacheTime: 24 * 60 * 60_000,
    freshnessLevel: 'fresh',
    requiresAuth: false,
    financialSensitive: false,
  },
} as const;

export const OPERATION_CLASSIFICATIONS: Record<string, OperationCategory> = {
  'GET /api/buildings/': 'read-only-cacheable',
  'GET /api/buildings/{id}/': 'read-only-cacheable',
  'GET /buildings/{id}/units/': 'read-only-cacheable',
  'GET /units/{id}/': 'read-only-cacheable',
  'GET /renters/': 'read-only-cacheable',
  'GET /renters/{id}/': 'read-only-cacheable',
  'GET /caretakers/': 'read-only-cacheable',
  'GET /caretakers/{id}/': 'read-only-cacheable',
  'GET /maintenance/': 'read-only-cacheable',
  'GET /maintenance/{id}/': 'read-only-cacheable',
  'GET /notifications/': 'read-only-cacheable',
  'GET /notifications/unread/': 'read-only-cacheable',
  'GET /dashboard/stats/': 'read-only-cacheable',
  'GET /dashboard/activity/': 'read-only-cacheable',
  'GET /dashboard/recent-rent/': 'read-only-cacheable',
  'GET /rent-records/': 'read-only-cacheable',
  'GET /rent-records/{id}/': 'read-only-cacheable',
  'GET /api/visitors/': 'read-only-cacheable',
  'GET /api/visitors/{id}/': 'read-only-cacheable',
  'GET /agreements/': 'read-only-cacheable',
  'GET /agreements/{id}/': 'read-only-cacheable',
  'GET /payments/': 'read-only-cacheable',
  'GET /payments/{id}/': 'read-only-cacheable',
  'GET /invoices/': 'read-only-cacheable',
  'GET /invoices/{id}/': 'read-only-cacheable',
  'GET /subscriptions/plans/': 'read-only-cacheable',
  'GET /subscriptions/current/': 'read-only-cacheable',
  'GET /api/documents/': 'read-only-cacheable',
  'GET /api/documents/{id}/': 'read-only-cacheable',
  'GET /api/search/': 'read-only-cacheable',
  'GET /api/search/suggestions/': 'read-only-cacheable',
  'GET /reports/financial/': 'read-only-cacheable',
  'GET /reports/occupancy/': 'read-only-cacheable',

  'POST /auth/login/': 'online-only',
  'POST /auth/send-otp/': 'online-only',
  'POST /auth/owner/verify-otp/': 'online-only',
  'POST /auth/renter/verify-otp/': 'online-only',
  'POST /auth/register/': 'online-only',
  'POST /auth/social/': 'online-only',
  'POST /api/token/refresh/': 'online-only',
  'POST /auth/logout/': 'online-only',
  'POST /auth/logout-all/': 'online-only',
  'POST /change-password/': 'online-only',
  'POST /forgot-password/': 'online-only',
  'POST /reset-password/': 'online-only',
  'POST /auth/biometric/setup/': 'online-only',
  'POST /auth/biometric/disable/': 'online-only',
  'POST /payments/initiate/': 'sensitive-financial',
  'POST /payments/verify/': 'sensitive-financial',
  'POST /payments/{id}/refund/': 'sensitive-financial',
  'POST /payments/': 'sensitive-financial',
  'POST /payments/{id}/': 'sensitive-financial',
  'DELETE /payments/{id}/': 'sensitive-financial',
  'POST /subscriptions/upgrade/': 'sensitive-financial',
  'POST /subscriptions/cancel/': 'sensitive-financial',
  'POST /add-ons/purchase/': 'sensitive-financial',
  'POST /api/owner/update-bank-details/': 'sensitive-financial',
  'POST /api/owner/retry_payout_api/{rent_id}/': 'sensitive-financial',
  'POST /rent-records/generate/': 'sensitive-financial',
  'POST /rent-records/': 'sensitive-financial',
  'POST /rent-records/{id}/': 'sensitive-financial',
  'DELETE /rent-records/{id}/': 'sensitive-financial',
  'POST /api/owner/update-alert-preferences/': 'online-only',
  'POST /properties/': 'online-only',
  'POST /properties/{id}/': 'online-only',
  'DELETE /properties/{id}/': 'online-only',
  'POST /api/buildings/': 'online-only',
  'POST /api/buildings/{id}/': 'online-only',
  'DELETE /api/buildings/{id}/': 'online-only',
  'POST /buildings/{id}/units/': 'online-only',
  'POST /units/{id}/': 'online-only',
  'DELETE /units/{id}/': 'online-only',
  'POST /renters/': 'offline-safe-mutation',
  'POST /renters/{id}/': 'offline-safe-mutation',
  'DELETE /renters/{id}/': 'online-only',
  'POST /renters/{id}/verify/': 'online-only',
  'POST /renters/{id}/blacklist/': 'online-only',
  'POST /renters/{id}/vacate/': 'online-only',
  'POST /caretakers/': 'online-only',
  'POST /caretakers/{id}/': 'online-only',
  'DELETE /caretakers/{id}/': 'online-only',
  'POST /api/visitors/': 'offline-safe-mutation',
  'POST /api/visitors/{id}/': 'offline-safe-mutation',
  'DELETE /api/visitors/{id}/': 'online-only',
  'POST /api/visitors/{id}/approve/': 'online-only',
  'POST /api/visitors/{id}/reject/': 'online-only',
  'POST /api/visitors/{id}/check-in/': 'online-only',
  'POST /api/visitors/{id}/check-out/': 'online-only',
  'POST /api/visitors/{id}/cancel/': 'online-only',
  'POST /api/visitors/{id}/block/': 'online-only',
  'POST /api/documents/': 'offline-safe-mutation',
  'POST /api/documents/{id}/': 'offline-safe-mutation',
  'DELETE /api/documents/{id}/': 'online-only',
  'POST /api/documents/bulk-delete/': 'online-only',
  'POST /notifications/mark/{notification_id}/': 'offline-safe-mutation',
  'POST /notifications/mark-all-read/': 'offline-safe-mutation',
  'POST /api/notifications/save-token/': 'offline-safe-mutation',
  'POST /api/notifications/register-fcm/': 'offline-safe-mutation',
  'POST /settings/preferences/': 'offline-safe-mutation',
  'POST /maintenance/': 'offline-safe-mutation',
  'POST /maintenance/{id}/': 'offline-safe-mutation',
  'DELETE /maintenance/{id}/': 'online-only',
  'POST /maintenance/{id}/comments/': 'offline-safe-mutation',
  'POST /agreements/': 'offline-safe-mutation',
  'POST /agreements/{id}/': 'offline-safe-mutation',
  'DELETE /agreements/{id}/': 'online-only',
};

export const ONLINE_ONLY_CATEGORIES: OperationCategory[] = ['online-only', 'sensitive-financial'];
export const OFFLINE_SAFE_CATEGORIES: OperationCategory[] = ['offline-safe-mutation'];
export const CACHEABLE_CATEGORIES: OperationCategory[] = ['read-only-cacheable'];
