import type { RentPaymentMethod, RentPaymentStatus, RentPayoutStatus, RentSortOption, RentStatusConfig, RentMethodConfig, RentPayoutStatusConfig } from '../types/rents';

export const RENT_CONSTANTS = {
  API: {
    LIST: '/rent-records/',
    DETAIL: (id: string | number) => `/rent-records/${id}/`,
    CREATE: '/rent-records/',
    UPDATE: (id: string | number) => `/rent-records/${id}/`,
    DELETE: (id: string | number) => `/rent-records/${id}/`,
    MONTHLY_SUMMARY: '/rent-records/monthly_rent_summary/',
    ITR_SUMMARY: '/rent-records/itr_summary/',
    SEND_ITR_SUMMARY: '/rent-records/send_itr_summary/',
    DOWNLOAD_ITR_SUMMARY: '/rent-records/download_itr_summary/',
    INVOICE: (id: string | number) => `/rent-records/${id}/invoice/`,
    RESEND_CONFIRMATION: (id: string | number) => `/rent-records/${id}/resend-confirmation/`,
    OWNER_LIST: '/owner/rent-records/',
    OWNER_OVERVIEW: '/owner/rents/',
    RETRY_PAYOUT: (id: string | number) => `/owner/retry_payout_api/${id}/`,
    RENTER_DUE: '/renter/rent-due/',
    RENTER_HISTORY: '/renter/rent-history/',
    RENTER_LIST: '/renter/rent-records/',
    RENTER_DETAIL: (id: string | number) => `/renter/rent-records/${id}/`,
  },
  PAYMENT: {
    CREATE: '/api/rent/payment/',
    VERIFY: '/api/rent/verify-payment/',
    CALLBACK: '/api/rent/payment-callback/',
  } as const,
  STATUSES: {
    PENDING: 'pending',
    PAID: 'paid',
    OVERDUE: 'overdue',
    CANCELLED: 'cancelled',
  } as const satisfies Record<string, RentPaymentStatus>,
  STATUS_LABELS: {
    pending: 'Pending',
    paid: 'Paid',
    overdue: 'Overdue',
    cancelled: 'Cancelled',
  } as const satisfies Record<RentPaymentStatus, string>,
  STATUS_CONFIG: {
    pending: {
      label: 'Pending',
      color: '#D97706',
      backgroundColor: '#FEF3C7',
      icon: 'clock-outline',
    },
    paid: {
      label: 'Paid',
      color: '#059669',
      backgroundColor: '#D1FAE5',
      icon: 'check-circle-outline',
    },
    overdue: {
      label: 'Overdue',
      color: '#DC2626',
      backgroundColor: '#FEE2E2',
      icon: 'alert-circle-outline',
    },
    cancelled: {
      label: 'Cancelled',
      color: '#6B7280',
      backgroundColor: '#F3F4F6',
      icon: 'cancel',
    },
  } as const satisfies Record<RentPaymentStatus, RentStatusConfig>,
  METHODS: {
    CASH: 'cash',
    BANK_TRANSFER: 'bank_transfer',
    UPI: 'upi',
    CHEQUE: 'cheque',
    CARD: 'card',
    ONLINE: 'online',
    OTHER: 'other',
  } as const satisfies Record<string, RentPaymentMethod>,
  METHOD_LABELS: {
    cash: 'Cash',
    bank_transfer: 'Bank Transfer',
    upi: 'UPI',
    cheque: 'Cheque',
    card: 'Card',
    online: 'Online Payment',
    other: 'Other',
  } as const satisfies Record<RentPaymentMethod, string>,
  METHOD_CONFIG: {
    cash: { label: 'Cash', icon: 'cash', color: '#059669' },
    bank_transfer: { label: 'Bank Transfer', icon: 'bank', color: '#2563EB' },
    upi: { label: 'UPI', icon: 'cellphone', color: '#7C3AED' },
    cheque: { label: 'Cheque', icon: 'checkbook', color: '#D97706' },
    card: { label: 'Card', icon: 'credit-card', color: '#DC2626' },
    online: { label: 'Online', icon: 'web', color: '#2563EB' },
    other: { label: 'Other', icon: 'dots-horizontal', color: '#6B7280' },
  } as const satisfies Record<RentPaymentMethod, RentMethodConfig>,
  PAYOUT_STATUSES: {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
  } as const satisfies Record<string, RentPayoutStatus>,
  PAYOUT_STATUS_LABELS: {
    PENDING: 'Pending',
    SUCCESS: 'Completed',
    FAILED: 'Failed',
  } as const satisfies Record<RentPayoutStatus, string>,
  PAYOUT_STATUS_CONFIG: {
    PENDING: { label: 'Pending', color: '#D97706', backgroundColor: '#FEF3C7' },
    SUCCESS: { label: 'Completed', color: '#059669', backgroundColor: '#D1FAE5' },
    FAILED: { label: 'Failed', color: '#DC2626', backgroundColor: '#FEE2E2' },
  } as const satisfies Record<RentPayoutStatus, RentPayoutStatusConfig>,
  SORT_OPTIONS: {
    NEWEST: 'newest',
    OLDEST: 'oldest',
    AMOUNT_HIGH: 'amount_high',
    AMOUNT_LOW: 'amount_low',
    DUE_DATE: 'due_date',
    STATUS: 'status',
  } as const satisfies Record<string, RentSortOption>,
  SORT_LABELS: {
    newest: 'Newest',
    oldest: 'Oldest',
    amount_high: 'Amount: High to Low',
    amount_low: 'Amount: Low to High',
    due_date: 'Due Date',
    status: 'Status',
  } as const satisfies Record<RentSortOption, string>,
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
  } as const,
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 10 * 60 * 1000,
  } as const,
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Unable to connect to the server. Please check your internet connection.',
    UNAUTHORIZED: 'You are not authorized. Please log in again.',
    FORBIDDEN: 'You do not have permission to perform this action.',
    NOT_FOUND: 'Rent record not found.',
    CONFLICT: 'This rent record already exists.',
    VALIDATION_ERROR: 'Please check the entered data.',
    RATE_LIMITED: 'Too many requests. Please try again later.',
    SERVER_ERROR: 'Server error. Please try again later.',
    GENERIC: 'Something went wrong. Please try again.',
    PAYMENT_INIT_FAILED: 'Failed to initiate payment. Please try again.',
    PAYMENT_VERIFY_FAILED: 'Payment verification failed. Please contact support.',
    PAYOUT_RETRY_FAILED: 'Failed to retry payout. Please try again.',
    INVOICE_DOWNLOAD_FAILED: 'Failed to download invoice. Please try again.',
  } as const,
  EMPTY_STATE: {
    NO_RECORDS: {
      title: 'No rent records found',
      description: 'Rent records will appear here once created.',
      actionLabel: 'Create Rent Record',
    },
    NO_PAYMENT_LINK: {
      title: 'No payment link',
      description: 'Payment link will be generated when rent record is created.',
    },
  } as const,
} as const;

export type RentConstants = typeof RENT_CONSTANTS;
