import type { UnitDocumentType } from '../types';

export const DOCUMENT_CONSTANTS = {
  API: {
    LIST_DOCUMENTS: '/properties/unit-all-documents/',
    CREATE_DOCUMENT: '/properties/unit-all-documents/',
    DETAIL_DOCUMENT: (id: number | string) => `/properties/unit-all-documents/${id}/`,
    UPDATE_DOCUMENT: (id: number | string) => `/properties/unit-all-documents/${id}/`,
    DELETE_DOCUMENT: (id: number | string) => `/properties/unit-all-documents/${id}/`,

    LIST_IMAGES: '/properties/unit-images/',
    CREATE_IMAGE: '/properties/unit-images/',
    DETAIL_IMAGE: (id: number | string) => `/properties/unit-images/${id}/`,
    UPDATE_IMAGE: (id: number | string) => `/properties/unit-images/${id}/`,
    DELETE_IMAGE: (id: number | string) => `/properties/unit-images/${id}/`,
  } as const,
  TYPE: {
    PDF: 'pdf',
    IMAGE: 'image',
    DOC: 'doc',
    DOCX: 'docx',
    EXCEL: 'excel',
    CSV: 'csv',
    TEXT: 'text',
    ZIP: 'zip',
    AUDIO: 'audio',
    VIDEO: 'video',
    OTHER: 'other',
  } as const satisfies Record<string, UnitDocumentType>,
  MIME_TYPES: {
    image: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    pdf: ['application/pdf'],
    doc: ['application/msword'],
    docx: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    excel: [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ],
    csv: ['text/csv', 'application/csv'],
    text: ['text/plain', 'text/markdown', 'text/html'],
    zip: ['application/zip', 'application/x-zip-compressed'],
    audio: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4'],
    video: ['video/mp4', 'video/webm', 'video/ogg'],
  } as const,
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/bmp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'application/zip',
    'text/plain',
  ] as const,
  MAX_FILE_SIZE: 50 * 1024 * 1024,
  MAX_DOCUMENTS_PER_UNIT: 5,
  MAX_IMAGES_PER_UNIT: 10,
  UPLOAD: {
    CHUNK_SIZE: 5 * 1024 * 1024,
    MAX_RETRIES: 3,
    RETRY_DELAY: 1000,
  },
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 5 * 60 * 1000,
  },
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Unable to connect. Please check your internet.',
    UNAUTHORIZED: 'Session expired. Please log in again.',
    FORBIDDEN: 'You do not have permission.',
    NOT_FOUND: 'Document not found.',
    VALIDATION_ERROR: 'Invalid file. Please check and try again.',
    SERVER_ERROR: 'Server error. Please try again later.',
    LIMIT_REACHED: 'Upload limit reached for this unit.',
    FILE_TOO_LARGE: 'File exceeds the 50MB size limit.',
    UNSUPPORTED_TYPE: 'File type not supported.',
    UPLOAD_FAILED: 'Upload failed. Please retry.',
    OFFLINE: 'You are offline.',
    GENERIC: 'Something went wrong. Please try again.',
  },
  SORT_OPTIONS: {
    NEWEST: 'newest',
    OLDEST: 'oldest',
    NAME_ASC: 'name_asc',
    NAME_DESC: 'name_desc',
  } as const satisfies Record<string, string>,
} as const;

export type DocumentConstants = typeof DOCUMENT_CONSTANTS;
