import type { DocumentType, DocumentStatus, DocumentSortField, SortOption, DocumentUploadProgress } from '../types';

export const DOCUMENT_CONSTANTS = {
  API: {
    LIST: '/api/documents/',
    DETAIL: (id: number | string) => `/api/documents/${id}/`,
    CREATE: '/api/documents/',
    UPDATE: (id: number | string) => `/api/documents/${id}/`,
    DELETE: (id: number | string) => `/api/documents/${id}/`,
    DOWNLOAD: (id: number | string) => `/api/documents/${id}/download/`,
    PREVIEW: (id: number | string) => `/api/documents/${id}/preview/`,
    UPLOAD: '/api/documents/upload/',
    MOVE: (id: number | string) => `/api/documents/${id}/move/`,
    COPY: (id: number | string) => `/api/documents/${id}/copy/`,
    SHARE: (id: number | string) => `/api/documents/${id}/share/`,
    FAVORITE: (id: number | string) => `/api/documents/${id}/favorite/`,
    ARCHIVE: (id: number | string) => `/api/documents/${id}/archive/`,
    RESTORE: (id: number | string) => `/api/documents/${id}/restore/`,
    VERSIONS: (id: number | string) => `/api/documents/${id}/versions/`,
    DUPLICATES: '/api/documents/duplicates/',
    FOLDERS: '/api/documents/folders/',
    USAGE_LIMITS: '/api/documents/usage-limits/',
    COMPRESS: '/api/documents/compress/',
    BULK_DELETE: '/api/documents/bulk-delete/',
    BULK_MOVE: '/api/documents/bulk-move/',
    BULK_DOWNLOAD: '/api/documents/bulk-download/',
    SEARCH: '/api/documents/search/',
    METADATA: (id: number | string) => `/api/documents/${id}/metadata/`,
  } as const,
  STATUS: {
    ACTIVE: 'active',
    ARCHIVED: 'archived',
    DELETED: 'deleted',
  } as const satisfies Record<string, DocumentStatus>,
  TYPE: {
    IMAGE: 'image',
    PDF: 'pdf',
    DOC: 'doc',
    DOCX: 'docx',
    EXCEL: 'excel',
    CSV: 'csv',
    ZIP: 'zip',
    TEXT: 'text',
    AUDIO: 'audio',
    VIDEO: 'video',
  } as const satisfies Record<string, DocumentType>,
  TYPE_LABELS: {
    image: 'Image',
    pdf: 'PDF',
    doc: 'DOC',
    docx: 'DOCX',
    excel: 'Excel',
    csv: 'CSV',
    zip: 'ZIP',
    text: 'Text',
    audio: 'Audio',
    video: 'Video',
  } as const,
  MIME_TYPES: {
    image: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    pdf: ['application/pdf'],
    doc: ['application/msword'],
    docx: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    excel: [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ],
    csv: ['text/csv', 'application/csv'],
    zip: ['application/zip', 'application/x-zip-compressed'],
    text: ['text/plain', 'text/markdown', 'text/html'],
    audio: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4'],
    video: ['video/mp4', 'video/webm', 'video/ogg'],
  } as const,
  MAX_FILE_SIZE: 50 * 1024 * 1024, // 50MB
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'application/zip',
    'text/plain',
    'audio/mpeg',
    'audio/wav',
    'video/mp4',
  ],
  SORT_OPTIONS: {
    NEWEST: 'newest',
    OLDEST: 'oldest',
    NAME_ASC: 'name_asc',
    NAME_DESC: 'name_desc',
    SIZE_ASC: 'size_asc',
    SIZE_DESC: 'size_desc',
    TYPE: 'type',
    FAVORITE: 'favorite',
  } as const satisfies Record<string, DocumentSortField>,
  SORT_LABELS: {
    newest: 'Newest First',
    oldest: 'Oldest First',
    name_asc: 'Name (A-Z)',
    name_desc: 'Name (Z-A)',
    size_asc: 'Size (Smallest)',
    size_desc: 'Size (Largest)',
    type: 'File Type',
    favorite: 'Favorites',
  } as const,
  FILTERS: {
    SEARCH: 'search',
    TYPE: 'type',
    PARENT: 'parent',
    FAVORITE: 'favorite',
    ARCHIVED: 'is_archived',
    DATE_FROM: 'date_from',
    DATE_TO: 'date_to',
  } as const,
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
  } as const,
  CACHE: {
    STALE_TIME: 2 * 60 * 1000,
    GC_TIME: 5 * 60 * 1000,
  } as const,
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Unable to connect. Please check your internet.',
    UNAUTHORIZED: 'Session expired. Please log in again.',
    FORBIDDEN: 'You do not have permission.',
    NOT_FOUND: 'Document not found.',
    CONFLICT: 'A document with this content already exists.',
    VALIDATION_ERROR: 'Invalid file. Please check and try again.',
    RATE_LIMITED: 'Too many requests. Please wait.',
    SERVER_ERROR: 'Server error. Please try again later.',
    MAINTENANCE: 'System under maintenance.',
    LIMIT_REACHED: 'Document upload limit reached.',
    FILE_TOO_LARGE: 'File exceeds the 50MB size limit.',
    UNSUPPORTED_TYPE: 'File type not supported.',
    UPLOAD_FAILED: 'Upload failed. Please retry.',
    OFFLINE: 'You are offline. Upload queued.',
    GENERIC: 'Something went wrong. Please try again.',
  } as const,
  EMPTY_STATE: {
    TITLE: 'No documents yet',
    DESCRIPTION: 'Upload your first document to get started.',
    ACTION_LABEL: 'Upload Document',
  } as const,
  STORAGE: {
    DOCUMENTS_CACHE: 'documents_cache',
    SELECTED_DOCUMENT: 'selected_document',
    FILTERS: 'documents_filters',
    UPLOAD_QUEUE: 'documents_upload_queue',
  } as const,
  UPLOAD: {
    CHUNK_SIZE: 5 * 1024 * 1024, // 5MB chunks for large files
    MAX_RETRIES: 3,
    RETRY_DELAY: 1000,
  } as const,
  THUMBNAIL: {
    SIZE: 256,
    FORMAT: 'png',
  } as const,
  COMPRESSION: {
    IMAGE_QUALITY: 85,
    PDF_DPI: 150,
  } as const,
};

export type DocumentConstants = typeof DOCUMENT_CONSTANTS;
