import type { RouteDefinition, UserRole, Permission } from '@/navigation/types';
import {
  ROUTE_NAMES,
  ROUTE_GROUPS,
  AUTH_ROUTES,
  PROTECTED_BASE,
} from '@/navigation/constants';
import type { DeepLinkType } from '@/navigation/types/navigation.types';

export const ROUTE_REGISTRY: RouteDefinition[] = [
  // Auth routes
  {
    name: ROUTE_NAMES.WELCOME,
    path: '/(auth)/welcome',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.LOGIN,
    path: '/(auth)/login',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.REGISTER,
    path: '/(auth)/register',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.FORGOT_PASSWORD,
    path: '/(auth)/forgot-password',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.OTP,
    path: '/(auth)/otp',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.VERIFY_OTP,
    path: '/(auth)/verify-otp',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.RESET_PASSWORD,
    path: '/(auth)/reset-password',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.CREATE_PASSWORD,
    path: '/(auth)/create-password',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.BIOMETRIC_SETUP,
    path: '/(auth)/biometric-setup',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.SESSION_EXPIRED,
    path: '/(auth)/session-expired',
    group: 'auth',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.MAINTENANCE,
    path: '/(auth)/maintenance',
    group: 'auth',
    isPublic: true,
  },
  // Public routes
  {
    name: ROUTE_NAMES.SPLASH,
    path: '/splash',
    group: 'public',
    isPublic: true,
  },
  {
    name: ROUTE_NAMES.NOT_FOUND,
    path: '/not-found',
    group: 'public',
    isPublic: true,
  },
  // Protected drawer routes
  {
    name: ROUTE_NAMES.DASHBOARD,
    path: '/(drawer)/(tabs)/dashboard',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
    featureKey: 'dashboard',
  },
  {
    name: ROUTE_NAMES.DASHBOARD_OWNER,
    path: '/(drawer)/(tabs)/dashboard/owner',
    group: 'drawer',
    requiredRoles: ['property_owner', 'admin', 'super_admin'],
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.DASHBOARD_CARETAKER,
    path: '/(drawer)/(tabs)/dashboard/caretaker',
    group: 'drawer',
    requiredRoles: ['caretaker'],
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.DASHBOARD_RENTER,
    path: '/(drawer)/(tabs)/dashboard/renter',
    group: 'drawer',
    requiredRoles: ['renter'],
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.PROPERTIES,
    path: '/(drawer)/(tabs)/properties',
    group: 'drawer',
    requiredPermissions: ['property:read'],
    featureKey: 'properties',
  },
  {
    name: ROUTE_NAMES.PROPERTIES_OWNER,
    path: '/(drawer)/(tabs)/properties/owner',
    group: 'drawer',
    requiredRoles: ['property_owner', 'admin', 'super_admin'],
    requiredPermissions: ['property:read'],
  },
  {
    name: ROUTE_NAMES.BUILDINGS,
    path: '/(drawer)/(tabs)/buildings',
    group: 'drawer',
    requiredPermissions: ['building:read'],
    featureKey: 'buildings',
  },
  {
    name: ROUTE_NAMES.BUILDINGS_LIST,
    path: '/(drawer)/(tabs)/buildings/list',
    group: 'drawer',
    requiredPermissions: ['building:read'],
  },
  {
    name: ROUTE_NAMES.BUILDING_DETAIL,
    path: '/(drawer)/(tabs)/buildings/[id]',
    group: 'drawer',
    requiredPermissions: ['building:read'],
    featureKey: 'buildings',
    deepLinkPattern: 'building/:id',
  },
  {
    name: ROUTE_NAMES.BUILDING_ADD,
    path: '/(drawer)/(tabs)/buildings/add',
    group: 'drawer',
    requiredPermissions: ['building:write'],
  },
  {
    name: ROUTE_NAMES.UNITS,
    path: '/(drawer)/(tabs)/units',
    group: 'drawer',
    requiredPermissions: ['unit:read'],
    featureKey: 'units',
  },
  {
    name: ROUTE_NAMES.UNITS_LIST,
    path: '/(drawer)/(tabs)/units/list',
    group: 'drawer',
    requiredPermissions: ['unit:read'],
  },
  {
    name: ROUTE_NAMES.UNIT_DETAIL,
    path: '/(drawer)/(tabs)/units/[id]',
    group: 'drawer',
    requiredPermissions: ['unit:read'],
    featureKey: 'units',
    deepLinkPattern: 'unit/:id',
  },
  {
    name: ROUTE_NAMES.UNIT_ADD,
    path: '/(drawer)/(tabs)/units/add',
    group: 'drawer',
    requiredPermissions: ['unit:write'],
  },
  {
    name: ROUTE_NAMES.RENTERS,
    path: '/(drawer)/(tabs)/renters',
    group: 'drawer',
    requiredPermissions: ['renter:read'],
    featureKey: 'renters',
  },
  {
    name: ROUTE_NAMES.RENTERS_LIST,
    path: '/(drawer)/(tabs)/renters/list',
    group: 'drawer',
    requiredPermissions: ['renter:read'],
  },
  {
    name: ROUTE_NAMES.RENTER_DETAIL,
    path: '/(drawer)/(tabs)/renters/[id]',
    group: 'drawer',
    requiredPermissions: ['renter:read'],
    featureKey: 'renters',
    deepLinkPattern: 'renter/:id',
  },
  {
    name: ROUTE_NAMES.RENTER_ADD,
    path: '/(drawer)/(tabs)/renters/add',
    group: 'drawer',
    requiredPermissions: ['renter:write'],
  },
  {
    name: ROUTE_NAMES.CARETAKERS,
    path: '/(drawer)/(tabs)/caretakers',
    group: 'drawer',
    requiredPermissions: ['caretaker:read'],
    featureKey: 'caretakers',
  },
  {
    name: ROUTE_NAMES.CARETAKERS_LIST,
    path: '/(drawer)/(tabs)/caretakers/list',
    group: 'drawer',
    requiredPermissions: ['caretaker:read'],
  },
  {
    name: ROUTE_NAMES.CARETAKER_DETAIL,
    path: '/(drawer)/(tabs)/caretakers/[id]',
    group: 'drawer',
    requiredPermissions: ['caretaker:read'],
    featureKey: 'caretakers',
    deepLinkPattern: 'caretaker/:id',
  },
  {
    name: ROUTE_NAMES.CARETAKER_ADD,
    path: '/(drawer)/(tabs)/caretakers/add',
    group: 'drawer',
    requiredPermissions: ['caretaker:write'],
  },
  {
    name: ROUTE_NAMES.PAYMENTS,
    path: '/(drawer)/(tabs)/payments',
    group: 'drawer',
    requiredPermissions: ['payment:read'],
    featureKey: 'payments',
  },
  {
    name: ROUTE_NAMES.PAYMENTS_OWNER,
    path: '/(drawer)/(tabs)/payments/owner',
    group: 'drawer',
    requiredRoles: ['property_owner', 'admin', 'super_admin'],
    requiredPermissions: ['payment:read'],
  },
  {
    name: ROUTE_NAMES.PAYMENTS_RENTER,
    path: '/(drawer)/(tabs)/payments/renter',
    group: 'drawer',
    requiredRoles: ['renter'],
    requiredPermissions: ['payment:read'],
  },
  {
    name: ROUTE_NAMES.PAY_RENT,
    path: '/(drawer)/(tabs)/payments/pay-rent',
    group: 'drawer',
    requiredRoles: ['renter'],
    requiredPermissions: ['payment:read'],
  },
  {
    name: ROUTE_NAMES.RENT_RECORD_DETAIL,
    path: '/(drawer)/(tabs)/payments/rent-record/[id]',
    group: 'drawer',
    requiredPermissions: ['payment:read'],
    featureKey: 'rent-records',
    deepLinkPattern: 'rent/:id',
  },
  {
    name: ROUTE_NAMES.RENT_DUE,
    path: '/(drawer)/(tabs)/payments/rent-due',
    group: 'drawer',
    requiredRoles: ['renter'],
    requiredPermissions: ['payment:read'],
  },
  {
    name: ROUTE_NAMES.RENT_HISTORY,
    path: '/(drawer)/(tabs)/payments/rent-history',
    group: 'drawer',
    requiredRoles: ['renter'],
    requiredPermissions: ['payment:read'],
  },
  {
    name: ROUTE_NAMES.AGREEMENTS,
    path: '/(drawer)/(tabs)/agreements',
    group: 'drawer',
    requiredPermissions: ['agreement:read'],
    featureKey: 'agreements',
  },
  {
    name: ROUTE_NAMES.AGREEMENTS_LIST,
    path: '/(drawer)/(tabs)/agreements/list',
    group: 'drawer',
    requiredPermissions: ['agreement:read'],
  },
  {
    name: ROUTE_NAMES.AGREEMENT_DETAIL,
    path: '/(drawer)/(tabs)/agreements/[id]',
    group: 'drawer',
    requiredPermissions: ['agreement:read'],
    featureKey: 'agreements',
    deepLinkPattern: 'agreement/:id',
  },
  {
    name: ROUTE_NAMES.MAINTENANCE_LIST,
    path: '/(drawer)/(tabs)/maintenance',
    group: 'drawer',
    requiredPermissions: ['maintenance:read'],
    featureKey: 'maintenance',
  },
  {
    name: ROUTE_NAMES.MAINTENANCE_DASHBOARD,
    path: '/(drawer)/(tabs)/maintenance/dashboard',
    group: 'drawer',
    requiredPermissions: ['maintenance:read'],
  },
  {
    name: ROUTE_NAMES.MAINTENANCE_DETAIL,
    path: '/(drawer)/(tabs)/maintenance/[id]',
    group: 'drawer',
    requiredPermissions: ['maintenance:read'],
    featureKey: 'maintenance',
    deepLinkPattern: 'maintenance/:id',
  },
  {
    name: ROUTE_NAMES.MAINTENANCE_CREATE,
    path: '/(drawer)/(tabs)/maintenance/create',
    group: 'drawer',
    requiredPermissions: ['maintenance:write'],
  },
  {
    name: ROUTE_NAMES.VISITORS,
    path: '/(drawer)/(tabs)/visitors',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
    featureKey: 'visitors',
  },
  {
    name: ROUTE_NAMES.VISITORS_LIST,
    path: '/(drawer)/(tabs)/visitors/list',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_DETAIL,
    path: '/(drawer)/(tabs)/visitors/[id]',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
    featureKey: 'visitors',
    deepLinkPattern: 'visitor/:id',
  },
  {
    name: ROUTE_NAMES.VISITOR_CREATE,
    path: '/(drawer)/(tabs)/visitors/create',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_ENTRY,
    path: '/(drawer)/(tabs)/visitors/entry',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_EXIT,
    path: '/(drawer)/(tabs)/visitors/exit',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_QR_DISPLAY,
    path: '/(drawer)/(tabs)/visitors/qr-display',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_QR_SCANNER,
    path: '/(drawer)/(tabs)/visitors/qr-scanner',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.VISITOR_VERIFY,
    path: '/(drawer)/(tabs)/visitors/verify',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: ROUTE_NAMES.NOTIFICATIONS,
    path: '/(drawer)/(tabs)/notifications',
    group: 'drawer',
    requiredPermissions: ['notification:read'],
    featureKey: 'notifications',
  },
  {
    name: ROUTE_NAMES.NOTIFICATIONS_LIST,
    path: '/(drawer)/(tabs)/notifications/list',
    group: 'drawer',
    requiredPermissions: ['notification:read'],
  },
  {
    name: ROUTE_NAMES.REPORTS,
    path: '/(drawer)/(tabs)/reports',
    group: 'drawer',
    requiredPermissions: ['report:read'],
    featureKey: 'reports',
  },
  {
    name: ROUTE_NAMES.REPORTS_FINANCIAL,
    path: '/(drawer)/(tabs)/reports/financial',
    group: 'drawer',
    requiredPermissions: ['report:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION,
    path: '/(drawer)/(tabs)/subscription',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
    featureKey: 'subscription',
    requiresSubscription: false,
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_PLANS,
    path: '/(drawer)/(tabs)/subscription/plans',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_CURRENT,
    path: '/(drawer)/(tabs)/subscription/current',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_UPGRADE,
    path: '/(drawer)/(tabs)/subscription/upgrade',
    group: 'drawer',
    requiredPermissions: ['subscription:write'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_DOWNGRADE,
    path: '/(drawer)/(tabs)/subscription/downgrade',
    group: 'drawer',
    requiredPermissions: ['subscription:write'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_CANCEL,
    path: '/(drawer)/(tabs)/subscription/cancel',
    group: 'drawer',
    requiredPermissions: ['subscription:write'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_RENEW,
    path: '/(drawer)/(tabs)/subscription/renew',
    group: 'drawer',
    requiredPermissions: ['subscription:write'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_INVOICES,
    path: '/(drawer)/(tabs)/subscription/invoices',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_ADD_ONS,
    path: '/(drawer)/(tabs)/subscription/add-ons',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_USAGE,
    path: '/(drawer)/(tabs)/subscription/usage',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_PAYMENT_HISTORY,
    path: '/(drawer)/(tabs)/subscription/payment-history',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_PAYMENT_STATUS,
    path: '/(drawer)/(tabs)/subscription/payment-status',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_EXPIRY,
    path: '/(drawer)/(tabs)/subscription/expiry',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.SUBSCRIPTION_COMPARE,
    path: '/(drawer)/(tabs)/subscription/compare',
    group: 'drawer',
    requiredPermissions: ['subscription:read'],
  },
  {
    name: ROUTE_NAMES.AI_ASSISTANT,
    path: '/(drawer)/(tabs)/ai-assistant',
    group: 'drawer',
    requiredPermissions: ['ai:read'],
    featureKey: 'ai-assistant',
  },
  {
    name: ROUTE_NAMES.AI_ASSISTANT_CHAT,
    path: '/(drawer)/(tabs)/ai-assistant/chat',
    group: 'drawer',
    requiredPermissions: ['ai:read'],
  },
  {
    name: ROUTE_NAMES.SEARCH,
    path: '/(drawer)/(tabs)/search',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
    featureKey: 'search',
  },
  {
    name: ROUTE_NAMES.SETTINGS,
    path: '/(drawer)/(tabs)/settings',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
    featureKey: 'settings',
  },
  {
    name: ROUTE_NAMES.SETTINGS_INDEX,
    path: '/(drawer)/(tabs)/settings/index',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_PROFILE,
    path: '/(drawer)/(tabs)/settings/profile',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_SECURITY,
    path: '/(drawer)/(tabs)/settings/security',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_NOTIFICATIONS,
    path: '/(drawer)/(tabs)/settings/notifications',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_DEVICES,
    path: '/(drawer)/(tabs)/settings/devices',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_LANGUAGE,
    path: '/(drawer)/(tabs)/settings/language',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_THEME,
    path: '/(drawer)/(tabs)/settings/theme',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_PRIVACY,
    path: '/(drawer)/(tabs)/settings/privacy',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_ABOUT,
    path: '/(drawer)/(tabs)/settings/about',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_HELP,
    path: '/(drawer)/(tabs)/settings/help',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_DELETE_ACCOUNT,
    path: '/(drawer)/(tabs)/settings/delete-account',
    group: 'drawer',
    requiredPermissions: ['settings:write'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_DEACTIVATE_ACCOUNT,
    path: '/(drawer)/(tabs)/settings/deactivate-account',
    group: 'drawer',
    requiredPermissions: ['settings:write'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_LOGIN_SESSIONS,
    path: '/(drawer)/(tabs)/settings/login-sessions',
    group: 'drawer',
    requiredPermissions: ['settings:read'],
  },
  {
    name: ROUTE_NAMES.SETTINGS_EDIT_PROFILE,
    path: '/(drawer)/(tabs)/settings/edit-profile',
    group: 'drawer',
    requiredPermissions: ['settings:write'],
  },
  {
    name: ROUTE_NAMES.PROFILE,
    path: '/(drawer)/(tabs)/profile',
    group: 'drawer',
    requiredPermissions: ['user:read'],
    featureKey: 'profile',
  },
  {
    name: ROUTE_NAMES.PROFILE_VIEW,
    path: '/(drawer)/(tabs)/profile/view',
    group: 'drawer',
    requiredPermissions: ['user:read'],
  },
  {
    name: ROUTE_NAMES.SUPPORT,
    path: '/(drawer)/(tabs)/support',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
    featureKey: 'support',
  },
  {
    name: ROUTE_NAMES.SUPPORT_TICKETS,
    path: '/(drawer)/(tabs)/support/tickets',
    group: 'drawer',
    requiredPermissions: ['dashboard:read'],
  },
  {
    name: 'payment-status',
    path: '/(drawer)/(tabs)/payment-status',
    group: 'drawer',
    requiredPermissions: ['payment:read'],
  },
  {
    name: 'invoice-detail',
    path: '/(drawer)/(tabs)/invoice-detail',
    group: 'drawer',
    requiredPermissions: ['payment:read'],
  },
];

export const ROUTE_MAP: Record<string, RouteDefinition> = ROUTE_REGISTRY.reduce(
  (acc, route) => {
    acc[route.name] = route;
    return acc;
  },
  {} as Record<string, RouteDefinition>
);

export const PATH_TO_ROUTE_MAP: Record<string, RouteDefinition> = ROUTE_REGISTRY.reduce(
  (acc, route) => {
    acc[route.path] = route;
    return acc;
  },
  {} as Record<string, RouteDefinition>
);
