export const NOTIFICATION_ENDPOINTS = {
  LIST: '/api/notifications/get/',
  MARK_READ: (id: number) => `/api/notifications/mark/${id}/`,
  MARK_ALL_READ: '/api/notifications/mark-all-read/',
  DELETE: (id: number) => `/api/notifications/${id}/`,
  UNREAD_COUNT: '/api/notifications/unread-count/',
  SAVE_TOKEN: '/api/notifications/save-token/',
  REGISTER_FCM: '/api/notifications/register-fcm/',
  PREFERENCES: '/api/notifications/preferences/',
  PREFERENCES_GET: '/api/notifications/preferences/',
  DEVICES: '/api/notifications/devices/',
  DEVICE_DELETE: (id: number) => `/api/notifications/devices/${id}/`,
  NOTIFICATION_TYPES: '/api/notifications/types/',
  WHATSAPP_LOGS: '/api/notifications/whatsapp-logs/',
  REMINDERS: '/api/notifications/reminders/',
  HISTORY: '/api/notifications/history/',
  BROADCASTS: '/api/notifications/broadcasts/',
} as const;
