import { API_ENDPOINTS } from '@/services/api/endpoints';

export const SETTINGS_ENDPOINTS = {
  PROFILE: API_ENDPOINTS.AUTH.PROFILE,
  CHANGE_PASSWORD: API_ENDPOINTS.AUTH.CHANGE_PASSWORD,
  LOGOUT: API_ENDPOINTS.AUTH.LOGOUT,
  LOGOUT_ALL: API_ENDPOINTS.AUTH.LOGOUT_ALL,
  DEACTIVATE_ACCOUNT: '/auth/deactivate/',
  DELETE_ACCOUNT: '/auth/delete/',
  NOTIFICATION_PREFERENCES: '/api/notifications/preferences/',
  NOTIFICATION_PREFERENCES_GET: '/api/notifications/preferences/',
  BIOMETRIC_SETUP: API_ENDPOINTS.AUTH.BIOMETRIC_SETUP,
  BIOMETRIC_DISABLE: API_ENDPOINTS.AUTH.BIOMETRIC_DISABLE,
  DEVICE_REGISTER: API_ENDPOINTS.AUTH.DEVICE_REGISTER,
  DEVICES_LIST: '/api/notifications/devices/',
  APP_VERSION: API_ENDPOINTS.AUTH.APP_VERSION,
  MAINTENANCE: API_ENDPOINTS.AUTH.MAINTENANCE,
  BOOTSTRAP: '/auth/bootstrap/',
  SUBSCRIPTION_PLANS: '/subscription-plans/',
  USER_SUBSCRIPTION: '/user-subscriptions/',
  ADD_ON_PURCHASES: '/addon-purchases/',
  USAGE_LIMITS: '/usage-limits/',
  RENTER_PROFILE: '/renter/profile/',
} as const;
